import { passionfruit, iitpatna } from "../assets/images";
import {
    contact,
    css,
    express,
    git,
    github,
    javascript,
    linkedin,
    mongodb,
    nextjs,
    nodejs,
    react,
    tailwindcss,
    typescript,
    python,
    cplusplus,
    postgresql,
    pytorch,
    redis,
    docker,
    mysql,
    langchain,
    openai,
    rabbitmq,
    mui,
    summiz,
    pricewise,
    snapgram,
    estate,
    threads,
    car,
    arrow,
} from "../assets/icons";

export const skills = [
    {
        imageUrl: javascript,
        name: "JavaScript",
        type: "Frontend",
    },
    {
        imageUrl: python,
        name: "Python",
        type: "AI / ML",
    },
    {
        imageUrl: cplusplus,
        name: "C++",
        type: "Backend",
    },
    {
        imageUrl: react,
        name: "React.js",
        type: "Frontend",
    },
    {
        imageUrl: nextjs,
        name: "Next.js",
        type: "Frontend",
    },
    {
        imageUrl: nodejs,
        name: "Node.js",
        type: "Backend",
    },
    {
        imageUrl: express,
        name: "Express.js",
        type: "Backend",
    },
    {
        imageUrl: typescript,
        name: "TypeScript",
        type: "Frontend",
    },
    {
        imageUrl: pytorch,
        name: "PyTorch",
        type: "AI / ML",
    },
    {
        imageUrl: mongodb,
        name: "MongoDB",
        type: "Database",
    },
    {
        imageUrl: postgresql,
        name: "PostgreSQL",
        type: "Database",
    },
    {
        imageUrl: tailwindcss,
        name: "Tailwind CSS",
        type: "Frontend",
    },
    {
        imageUrl: git,
        name: "Git",
        type: "Version Control",
    },
    {
        imageUrl: github,
        name: "GitHub",
        type: "Version Control",
    },
    {
        imageUrl: css,
        name: "CSS",
        type: "Frontend",
    },
    {
        imageUrl: redis,
        name: "Redis",
        type: "Database",
    },
    {
        imageUrl: docker,
        name: "Docker",
        type: "DevOps",
    },
    {
        imageUrl: mysql,
        name: "MySQL",
        type: "Database",
    },
    {
        imageUrl: rabbitmq,
        name: "RabbitMQ",
        type: "Backend",
    },
    {
        imageUrl: mui,
        name: "Material UI",
        type: "Frontend",
    },
    {
        imageUrl: langchain,
        name: "LangChain",
        type: "AI / ML",
    },
    {
        imageUrl: openai,
        name: "OpenAI API",
        type: "AI / ML",
    },
];

export const experiences = [
    {
        title: "Founding Engineer & Full Stack Dev (AI/ML + Data Platforms)",
        company_name: "Passionfruit",
        company_link: "https://www.linkedin.com/company/getpassionfruit/posts/?feedView=all",
        icon: passionfruit,
        iconBg: "#ffd6d6",
        date: "July 2024 – Present",
        points: [
            "Built scalable backend architecture and 100+ REST APIs from scratch, powering analytics, reporting, and AI-driven insights.",
            "Integrated Google Search Console + GA4 pipelines end-to-end, enabling automated tracking across 200+ sites.",
            "Engineered cron + RabbitMQ workflows to process 10K+ jobs/day with retries and fail-safe execution.",
            "Shipped automated email reporting via Mailgun, delivering scheduled digests to 30+ stakeholders.",
            "Optimized DB performance via indexing, pagination, caching — reducing API latency by 40%.",
        ],
    },
    {
        title: "ML Research Intern",
        company_name: "IIT Patna",
        company_link: "https://www.iitp.ac.in",
        icon: iitpatna,
        iconBg: "#d6e4ff",
        date: "Dec 2023 – Aug 2024",
        points: [
            "Pioneered GrabPhisher — Ethereum phishing detection using EvolveGCN + Node2vec.",
            "Achieved 93% accuracy and 92% F1-score, outperforming all state-of-the-art methods.",
            "Constructed TNG & TTNG to capture dynamic temporal features and evolving graph topology.",
            "Research accepted and published at an international conference.",
        ],
    },
];

export const socialLinks = [
    {
        name: 'Contact',
        iconUrl: contact,
        link: '/contact',
    },
    {
        name: 'GitHub',
        iconUrl: github,
        link: 'https://github.com/SiddharthFulia',
    },
    {
        name: 'LinkedIn',
        iconUrl: linkedin,
        link: 'https://www.linkedin.com/in/siddharth-fulia/',
    },
];

export const projects = [
    {
        iconUrl: summiz,
        theme: 'btn-back-blue',
        name: 'CrickSpeakAI',
        description: 'AI-powered cricket analytics platform with real-time commentary. ShotSense CNN (16 conv layers) for shot classification, CatchVision LSTM for 92% catch prediction, and LLM-powered live commentary.',
        link: null,
        linkLabel: null,
        tag: 'Research · Accepted',
    },
    {
        iconUrl: pricewise,
        theme: 'btn-back-red',
        name: 'GrabPhisher',
        description: 'Ethereum blockchain phishing detection using EvolveGCN + Node2vec. 93% accuracy, 92% F1-score — outperforms all SOTA methods. Built at IIT Patna.',
        link: 'https://github.com/SiddharthFulia',
        linkLabel: 'GitHub',
        tag: 'Research · Published',
    },
    {
        iconUrl: snapgram,
        theme: 'btn-back-pink',
        name: 'Quantum-Resistant Cryptography',
        description: 'Proprietary encryption algorithm that withstands quantum brute-force attacks, handles files up to 100MB+, and beats AES in space and time efficiency.',
        link: null,
        linkLabel: null,
        tag: 'Research · Accepted',
    },
    {
        iconUrl: estate,
        theme: 'btn-back-green',
        name: 'IoT Soil Testing & Crop Recommender',
        description: 'Arduino + ML system for real-time soil testing and AI crop recommendations. 50% efficiency boost, 30% productivity increase. Published on IEEE Xplore.',
        link: 'https://ieeexplore.ieee.org/document/10307726',
        linkLabel: 'Read Paper',
        tag: 'IEEE Published',
    },
    {
        iconUrl: threads,
        theme: 'btn-back-black',
        name: 'Passionfruit Platform',
        description: 'Full-stack SaaS at Passionfruit NY — 100+ APIs, GA4 across 200+ sites, RabbitMQ processing 10K+ jobs/day, Mailgun digests for 30+ stakeholders.',
        link: 'https://www.linkedin.com/company/getpassionfruit/posts/?feedView=all',
        linkLabel: 'View Company',
        tag: 'Production · Live',
    },
    {
        iconUrl: car,
        theme: 'btn-back-orange',
        name: 'Chess Platform',
        description: 'Full chess workspace · Stockfish 17 WASM in-browser · 10 modes: Standard / Chess960 / King-of-the-Hill / Three-Check / Atomic / Antichess / Horde / Crazyhouse / Racing Kings / Offline 2-Player · 3,700+ named openings with Lichess master-game explorer · 100,000+ Lichess puzzles with per-user ELO + retry scoring · Online multiplayer with takeback-request approval + clocks · MultiPV analysis · Save+replay across every variant · Per-side auto-queen · Refresh-resilient.',
        link: 'https://github.com/SiddharthFulia/Chess-engine',
        linkLabel: 'GitHub',
        tag: 'Full Suite · Engine · Variants · Multiplayer',
    },
    {
        iconUrl: car,
        theme: 'btn-back-yellow',
        name: 'LTTS Knowledge Graph',
        description: 'Automated Knowledge Graph extraction from unstructured documents. Top 3 out of 30,000+ participants from 480+ universities at LTTS TECHgium 2022.',
        link: 'https://drive.google.com/file/d/1C-4jtHmv-bGxPHo-0KYpnc8rdv1_Bc2C/view?usp=sharing',
        linkLabel: 'View Certificate',
        tag: 'Top 3 · TECHgium',
    },
    // ── AI / ML / RAG ──
    {
        name: 'realism-prompt-engine',
        description: 'Prompt engineering toolkit for photoreal image generation. Style presets, camera/lens tokens, and negative-prompt libraries for SDXL and Flux.',
        link: 'https://github.com/SiddharthFulia/realism-prompt-engine',
        linkLabel: 'GitHub',
        tag: 'AI · OSS',
    },
    {
        name: 'groq-llm-router',
        description: 'Drop-in router across Groq models (8B-instant, 70B-versatile, 120B). Latency-aware fallback, token budgeting, and streaming SSE.',
        link: 'https://github.com/SiddharthFulia/groq-llm-router',
        linkLabel: 'GitHub',
        tag: 'AI · OSS',
    },
    {
        name: 'rag-cinematic',
        description: 'RAG pipeline over film scripts and shot lists. Scene-aware chunking, character embeddings, and retrieval tuned for narrative continuity.',
        link: 'https://github.com/SiddharthFulia/rag-cinematic',
        linkLabel: 'GitHub',
        tag: 'AI · OSS',
    },
    {
        name: 'rag-codebase-search',
        description: 'Local RAG over source trees. AST-aware chunking, symbol indexing, and hybrid BM25 + dense retrieval for code Q&A.',
        link: 'https://github.com/SiddharthFulia/rag-codebase-search',
        linkLabel: 'GitHub',
        tag: 'AI · OSS',
    },
    {
        name: 'prompt-arena',
        description: 'Side-by-side prompt evaluation harness. Runs the same prompt across N models, scores with rubrics, exports diff reports.',
        link: 'https://github.com/SiddharthFulia/prompt-arena',
        linkLabel: 'GitHub',
        tag: 'AI · OSS',
    },
    {
        name: 'face-consistency-toolkit',
        description: 'Identity-preservation utilities for diffusion pipelines. ArcFace embedding checks, IP-Adapter prep, and drift scoring across frames.',
        link: 'https://github.com/SiddharthFulia/face-consistency-toolkit',
        linkLabel: 'GitHub',
        tag: 'AI · OSS',
    },
    {
        name: 'comfyui-job-queue',
        description: 'Redis-backed job queue in front of ComfyUI. Priority lanes, GPU pinning, retry on OOM, and webhook callbacks on completion.',
        link: 'https://github.com/SiddharthFulia/comfyui-job-queue',
        linkLabel: 'GitHub',
        tag: 'AI · OSS',
    },
    {
        name: 'wan-i2v-cli',
        description: 'Command-line wrapper around Wan image-to-video. Batch I2V jobs from a CSV of prompts + start frames with seed control.',
        link: 'https://github.com/SiddharthFulia/wan-i2v-cli',
        linkLabel: 'GitHub',
        tag: 'AI · OSS',
    },
    {
        name: 'comfy-workflow-builder',
        description: 'Programmatic builder for ComfyUI graph JSON. Compose nodes in TypeScript, validate connections, and emit ready-to-run workflows.',
        link: 'https://github.com/SiddharthFulia/comfy-workflow-builder',
        linkLabel: 'GitHub',
        tag: 'AI · OSS',
    },
    // ── Video / FFmpeg ──
    {
        name: 'ffmpeg-edit-server',
        description: 'HTTP service wrapping FFmpeg for trim, concat, mix, and overlay ops. Job-based API with progress streaming and presigned uploads.',
        link: 'https://github.com/SiddharthFulia/ffmpeg-edit-server',
        linkLabel: 'GitHub',
        tag: 'Video · OSS',
    },
    {
        name: 'video-poster-frames',
        description: 'Extracts representative poster frames from any video. Scene-score based picking with FFmpeg + perceptual hash dedup.',
        link: 'https://github.com/SiddharthFulia/video-poster-frames',
        linkLabel: 'GitHub',
        tag: 'Video · OSS',
    },
    {
        name: 'scene-cut-detector',
        description: 'Fast shot boundary detection via FFmpeg scene scores + histogram diff. Outputs cut list as JSON / EDL / CSV.',
        link: 'https://github.com/SiddharthFulia/scene-cut-detector',
        linkLabel: 'GitHub',
        tag: 'Video · OSS',
    },
    {
        name: 'vfx-grain-lavfi',
        description: 'Film grain and halation FFmpeg lavfi filter chains. Stock-style 16mm/35mm presets, fully GPU-friendly with no external deps.',
        link: 'https://github.com/SiddharthFulia/vfx-grain-lavfi',
        linkLabel: 'GitHub',
        tag: 'Video · OSS',
    },
    {
        name: 'kinetic-text-ffmpeg',
        description: 'Kinetic typography rendered entirely in FFmpeg. Timed word reveals, easing, and per-syllable highlights via drawtext + expressions.',
        link: 'https://github.com/SiddharthFulia/kinetic-text-ffmpeg',
        linkLabel: 'GitHub',
        tag: 'Video · OSS',
    },
    {
        name: 'webcodecs-mp4-stitcher',
        description: 'In-browser MP4 stitcher using WebCodecs + mp4box. Concatenates clips without re-encoding, runs fully client-side.',
        link: 'https://github.com/SiddharthFulia/webcodecs-mp4-stitcher',
        linkLabel: 'GitHub',
        tag: 'Video · OSS',
    },
    {
        name: 'rife-frame-bridge',
        description: 'RIFE-based frame interpolation pipeline. Bridges low-fps generations to smooth 60fps with edge-aware blending.',
        link: 'https://github.com/SiddharthFulia/rife-frame-bridge',
        linkLabel: 'GitHub',
        tag: 'Video · OSS',
    },
    // ── 3D / Splat ──
    {
        name: 'handflow-3d',
        description: 'Real-time hand tracking driving Three.js scenes. MediaPipe Hands → joint quaternions → rigged 3D puppet in the browser.',
        link: 'https://github.com/SiddharthFulia/handflow-3d',
        linkLabel: 'GitHub',
        tag: '3D · OSS',
    },
    {
        name: 'gaussian-splat-cache',
        description: 'CDN-friendly cache layer for .splat / .ply Gaussian Splat assets. Tile streaming, LOD selection, and ETag-aware invalidation.',
        link: 'https://github.com/SiddharthFulia/gaussian-splat-cache',
        linkLabel: 'GitHub',
        tag: '3D · OSS',
    },
    {
        name: 'splat-trimmer',
        description: 'CLI to crop, denoise, and downsample Gaussian Splat scenes. Bounding-box trim, opacity floor, and SH-band reduction.',
        link: 'https://github.com/SiddharthFulia/splat-trimmer',
        linkLabel: 'GitHub',
        tag: '3D · OSS',
    },
    // ── Frontend ──
    {
        name: 'scroll-cinematic-hero',
        description: 'GSAP + Framer Motion scroll-driven hero blocks. Pinned timelines, parallax layers, and reduced-motion fallbacks.',
        link: 'https://github.com/SiddharthFulia/scroll-cinematic-hero',
        linkLabel: 'GitHub',
        tag: 'Frontend · OSS',
    },
    {
        name: 'vault-context-react',
        description: 'Encrypted React context for client-side secrets. AES-GCM with WebCrypto, session-scoped keys, and ergonomic hooks.',
        link: 'https://github.com/SiddharthFulia/vault-context-react',
        linkLabel: 'GitHub',
        tag: 'Frontend · OSS',
    },
    {
        name: 'gsap-chapter-reel',
        description: 'Chapter-based scroll storytelling component. Snap-to-section, progress dots, and GSAP ScrollTrigger orchestration.',
        link: 'https://github.com/SiddharthFulia/gsap-chapter-reel',
        linkLabel: 'GitHub',
        tag: 'Frontend · OSS',
    },
];

export const publications = [
    {
        emoji: '🔐',
        title: 'Quantum-Resistant Cryptography: Proprietary Algorithm Outperforming AES',
        status: 'Accepted',
        statusBg: 'bg-purple-100 text-purple-700',
        conference: 'International Journal · 2024',
        link: null,
        linkLabel: null,
        highlights: [
            'Defies quantum threats with incomplete randomness techniques',
            'Handles images & documents up to 100MB+ with support for larger files',
            'Reduces space & time vs AES, unbreakable against brute-force attacks',
        ],
        theme: 'btn-back-pink',
    },
    {
        emoji: '🌱',
        title: 'Innovative Model For Soil Testing With Intelligent Crop Recommendation System',
        status: 'Published',
        statusBg: 'bg-green-100 text-green-700',
        conference: 'IEEE Xplore · 2023',
        link: 'https://ieeexplore.ieee.org/document/10307726',
        linkLabel: 'Read Paper',
        highlights: [
            'IoT + AI for infinite cycles of instant, accurate soil analysis',
            'Boosted operational efficiency by 50%, agricultural productivity by 30%',
            'Stack: Arduino IDE, NodeJS, React Native',
        ],
        theme: 'btn-back-green',
    },
    {
        emoji: '🏏',
        title: 'CrickSpeakAI: Revolutionizing Cricket Analytics and Commentary',
        status: 'Accepted',
        statusBg: 'bg-blue-100 text-blue-700',
        conference: 'International Conference · 2024',
        link: null,
        linkLabel: null,
        highlights: [
            'ShotSense CNN: 16 conv + 11 dense layers with VGG weights for shot classification',
            'CatchVision LSTM: 92% accuracy spatial-temporal catch prediction',
            'End-to-end YOLO v8 + LLM + GTTS real-time commentary pipeline',
        ],
        theme: 'btn-back-blue',
    },
];

export const achievements = [
    {
        emoji: '🏆',
        title: 'Meta Hacker Cup 2025',
        rank: 'Global Rank 186',
        sub: 'Round 3 · Two-time commemorative shirt recipient',
        certLink: 'https://www.facebook.com/codingcompetitions/hacker-cup/2025/certificate/5471687682871051?source=facebook',
        linkedinLink: 'https://www.linkedin.com/posts/siddharth-fulia_metahackercup2025-top200-round3-activity-7432281275920728066-5b8P?utm_source=share&utm_medium=member_desktop&rcm=ACoAADbS-ywBYuwbaIFL7brrtMs_7hHq9KiB_bw',
        theme: 'btn-back-yellow',
    },
    {
        emoji: '🥇',
        title: 'Meta Hacker Cup 2023',
        rank: 'Global Rank 1361',
        sub: 'Meta\'s global competitive programming competition',
        certLink: 'https://www.facebook.com/codingcompetitions/hacker-cup/2023/certificate/5471687682871051',
        linkedinLink: 'https://www.linkedin.com/posts/siddharth-fulia_metahackercup2023-finalranking-solocontender-activity-7135667127939739648-E3yJ?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAADbS-ywBYuwbaIFL7brrtMs_7hHq9KiB_bw',
        theme: 'btn-back-orange',
    },
    {
        emoji: '🎯',
        title: 'LTTS TECHgium 2022',
        rank: 'Top 3',
        sub: '"Knowledge Graph from Documents" · 30,000+ participants · 480+ universities worldwide',
        certLink: 'https://drive.google.com/file/d/1C-4jtHmv-bGxPHo-0KYpnc8rdv1_Bc2C/view?usp=sharing',
        linkedinLink: 'https://www.linkedin.com/posts/siddharth-fulia_ltts-techgium2023-finalists-activity-7098932401522786304-Tk6m?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAADbS-ywBYuwbaIFL7brrtMs_7hHq9KiB_bw',
        theme: 'btn-back-red',
    },
];

export const competitiveProgramming = [
    {
        platform: 'CodeChef',
        emoji: '👨‍💻',
        rating: '2114',
        stars: '5★',
        highlight: 'Global Rank 23',
        highlightSub: 'in CodeChef Starters',
        stats: [
            { label: 'Rating', value: '2114' },
            { label: 'Stars', value: '5★' },
            { label: 'Global Rank', value: '#23' },
            { label: 'Problems', value: '41+' },
        ],
        description: '5-star rated competitive programmer with a peak rating of 2114. Achieved Global Rank 23 in CodeChef Starters. Strong expertise in DP, greedy algorithms, binary search, and graph theory.',
        profileLink: 'https://www.codechef.com/users/fulia',
        linkedinLink: 'https://www.linkedin.com/posts/siddharth-fulia_back-in-the-arena-my-competitive-coding-activity-7339460576152039425-t4eR?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAADbS-ywBYuwbaIFL7brrtMs_7hHq9KiB_bw',
        color: 'from-yellow-400 to-orange-500',
        border: 'border-yellow-200',
        badge: 'bg-yellow-100 text-yellow-800',
    },
    {
        platform: 'Codeforces',
        emoji: '⚡',
        rating: 'Active',
        stars: '',
        highlight: 'Regular Competitor',
        highlightSub: 'Codeforces rated contests',
        stats: [
            { label: 'Platform', value: 'CF' },
            { label: 'Focus', value: 'DSA' },
            { label: 'Style', value: 'Speed' },
            { label: 'Contests', value: 'Rated' },
        ],
        description: 'Active Codeforces participant competing in rated rounds. Consistent practice in competitive problem solving with focus on algorithm optimization and mathematical reasoning.',
        profileLink: 'https://codeforces.com/profile/Fulia6464',
        linkedinLink: null,
        color: 'from-blue-400 to-indigo-500',
        border: 'border-blue-200',
        badge: 'bg-blue-100 text-blue-800',
    },
];
