export { default as Home } from './Home';
export { default as About } from './About';
export { default as Projects } from './Projects';
export { default as Contact } from './Contact';
export { default as Lab } from './Lab';
export { default as Learn } from './Learn';
export { default as Creative } from './Creative';
export { default as ChessViz } from './ChessViz';
export { default as Science } from './Science';
