// OSINT Powerhouse — 150+ open-source intel APIs at your fingertips.
//
// v3 layout (post-UX-upgrade):
//   • Compressed hero: single-line header with live pulse dot showing
//     "N tools · M live feeds · updated Xs ago"
//   • Tight telemetry strip (2/3/6 col responsive)
//   • Sticky filter + search bar (Tabs: Live · Tools · Catalog)
//   • All 32 tools auto-fire on mount with sensible defaults (staggered)
//   • Each tool result runs through a custom viz component from
//     `src/components/osint/viz/` — no more raw JSON dumps
//   • Raw JSON is a collapsible footer inside every viz
//
// The catalog JSON is generated by `scripts/sync-osint-catalog.js` — re-run
// that whenever E:/Siddharth/osint/framework.json changes.

import { useEffect, useMemo, useState, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Collapse, Input, Tag, Segmented, Progress, Empty,
  Tooltip, Badge, InputNumber, Tabs,
} from 'antd'
import {
  ThunderboltFilled, FireFilled, RocketFilled, GlobalOutlined,
  AlertOutlined, SearchOutlined, LinkOutlined,
  SafetyCertificateFilled, UserOutlined, ApiOutlined,
  PlayCircleFilled,
  CheckCircleFilled, CloseCircleFilled, ExclamationCircleFilled,
  ExperimentOutlined,
} from '@ant-design/icons'
import { Button } from '../components/ui'
import { LuxeLoader } from '../components/loaders'
import { pickViz } from '../components/osint/viz'
import { TOOL_DEFAULTS, STAGGER_MS, KICKOFF_DELAY_MS } from '../components/osint/defaults'

import catalog from '../constants/osintCatalog.json'

// ── BE URL helper ─────────────────────────────────────────────
// Not going through src/api/request.js because those helpers throw on any
// non-2xx — but individual OSINT endpoints (breach without HIBP key,
// domain without Host.io key) legitimately return 501 and we want to show
// a graceful "not configured" state instead of a red toast.
const BE_URL = import.meta.env.VITE_BE_URL || 'http://localhost:4001'

async function osintGet(path) {
  const res = await fetch(`${BE_URL}/api/osint${path}`, {
    headers: { Accept: 'application/json' },
  })
  const ct = res.headers.get('content-type') || ''
  const body = ct.includes('application/json') ? await res.json().catch(() => null) : null
  if (!res.ok) {
    const err = new Error(body?.error || `HTTP ${res.status}`)
    err.status = res.status
    err.body = body
    throw err
  }
  return body
}

// ── Live telemetry (6 widgets, polling every 30 s) ──────────
function useLiveTelemetry() {
  const [state, setState] = useState({
    eq   : { loading: true, data: null, ping: 0 },
    fires: { loading: true, data: null, ping: 0 },
    iss  : { loading: true, data: null, ping: 0 },
    astros:{ loading: true, data: null, ping: 0 },
    alerts:{ loading: true, data: null, ping: 0 },
  })
  const [countries, setCountries] = useState({ loading: true, data: null, ping: 0 })

  const load = async () => {
    const now = () => Date.now()
    const [eq, fires, iss, astros, alerts] = await Promise.allSettled([
      osintGet('/earthquakes?window=hour'),
      osintGet('/eonet?days=10&limit=200'),
      osintGet('/iss'),
      osintGet('/astros'),
      osintGet('/weather-alerts'),
    ])
    setState((s) => ({
      eq    : eq.status     === 'fulfilled' ? { loading: false, data: eq.value,     ping: now() } : { ...s.eq,     loading: false },
      fires : fires.status  === 'fulfilled' ? { loading: false, data: fires.value,  ping: now() } : { ...s.fires,  loading: false },
      iss   : iss.status    === 'fulfilled' ? { loading: false, data: iss.value,    ping: now() } : { ...s.iss,    loading: false },
      astros: astros.status === 'fulfilled' ? { loading: false, data: astros.value, ping: now() } : { ...s.astros, loading: false },
      alerts: alerts.status === 'fulfilled' ? { loading: false, data: alerts.value, ping: now() } : { ...s.alerts, loading: false },
    }))
  }

  useEffect(() => {
    load()
    const t = setInterval(load, 30_000)
    return () => clearInterval(t)
  }, [])

  useEffect(() => {
    osintGet('/countries')
      .then((data) => setCountries({ loading: false, data, ping: Date.now() }))
      .catch(() => setCountries((c) => ({ ...c, loading: false })))
  }, [])

  const lastUpdate = Math.max(state.eq.ping, state.fires.ping, state.iss.ping, state.astros.ping, state.alerts.ping)
  return { ...state, countries, lastUpdate }
}

// ── UI atoms ─────────────────────────────────────────────────
const StatCard = ({ icon, label, value, ctx, tone = 'amber', loading, updated }) => {
  const toneMap = {
    amber   : 'from-amber-400/25 to-rose-500/10 border-amber-400/25 text-amber-300',
    rose    : 'from-rose-500/25 to-fuchsia-500/10 border-rose-500/25 text-rose-300',
    fuchsia : 'from-fuchsia-500/25 to-violet-500/10 border-fuchsia-500/25 text-fuchsia-300',
    violet  : 'from-violet-500/25 to-indigo-500/10 border-violet-500/25 text-violet-300',
    cyan    : 'from-cyan-500/25 to-sky-500/10 border-cyan-500/25 text-cyan-300',
    emerald : 'from-emerald-500/25 to-teal-500/10 border-emerald-500/25 text-emerald-300',
  }
  return (
    <div className={`luxe-glass relative overflow-hidden border rounded-xl p-2.5 sm:p-3 bg-gradient-to-br ${toneMap[tone]}`}>
      <div className='flex items-center gap-1.5 mb-0.5'>
        <span className='opacity-90 text-xs'>{icon}</span>
        <span className='text-[9px] uppercase tracking-widest text-gray-400 font-bold truncate'>{label}</span>
      </div>
      {loading ? (
        <div className='py-1'><LuxeLoader variant='osint' size='sm' /></div>
      ) : (
        <motion.div
          key={String(value)}
          initial={{ opacity: 0, y: 4 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
          className='text-white font-bold text-base sm:text-lg leading-tight truncate'
          title={String(value)}
        >
          {value}
        </motion.div>
      )}
      {ctx && <div className='text-[9px] text-gray-400 mt-0.5 leading-snug line-clamp-1'>{ctx}</div>}
      {updated && (
        <div className='absolute top-1.5 right-2 h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_6px_rgba(52,211,153,0.9)]' />
      )}
    </div>
  )
}

const PricingTag = ({ pricing }) => {
  const p = (pricing || 'unknown').toLowerCase()
  if (p === 'free') return <Tag color='green'>FREE</Tag>
  if (p === 'freemium' || p === 'free/freemium') return <Tag color='cyan'>FREEMIUM</Tag>
  if (p === 'paid') return <Tag color='orange'>PAID</Tag>
  return <Tag color='default'>?</Tag>
}

// ── Telemetry strip (compact) ────────────────────────────────
const TelemetryStrip = ({ telemetry }) => {
  const t = telemetry
  const eqCount = t.eq.data?.features?.length ?? 0
  const eqMax = t.eq.data?.features?.reduce((m, f) => Math.max(m, f.properties?.mag ?? 0), 0)
  const eonetEvents = t.fires.data?.events ?? []
  const wildfireCount = eonetEvents.filter((e) => (e.categories || []).some((c) => /fire/i.test(c.title))).length
  const iss = t.iss.data?.iss_position
  const issTxt = iss ? `${(+iss.latitude).toFixed(1)}, ${(+iss.longitude).toFixed(1)}` : '—'
  const astros = t.astros.data?.number ?? 0
  const alertCount = t.alerts.data?.features?.length ?? 0
  const countryCount = t.countries.data?.length ?? 0

  return (
    <div className='grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2'>
      <StatCard icon={<ThunderboltFilled />} tone='amber' label='EQ / hr' value={t.eq.loading ? '' : eqCount} ctx={eqCount ? `max ${eqMax?.toFixed(1)}` : 'USGS'} loading={t.eq.loading} updated={!!t.eq.ping} />
      <StatCard icon={<FireFilled />} tone='rose' label='Wildfires' value={t.fires.loading ? '' : wildfireCount} ctx='NASA EONET' loading={t.fires.loading} updated={!!t.fires.ping} />
      <StatCard icon={<RocketFilled />} tone='cyan' label='ISS' value={t.iss.loading ? '' : issTxt} ctx='live lat/lng' loading={t.iss.loading} updated={!!t.iss.ping} />
      <StatCard icon={<UserOutlined />} tone='violet' label='Astros' value={t.astros.loading ? '' : astros} ctx='orbiting' loading={t.astros.loading} updated={!!t.astros.ping} />
      <StatCard icon={<AlertOutlined />} tone='fuchsia' label='US alerts' value={t.alerts.loading ? '' : alertCount} ctx='NOAA' loading={t.alerts.loading} updated={!!t.alerts.ping} />
      <StatCard icon={<GlobalOutlined />} tone='emerald' label='Countries' value={t.countries.loading ? '' : countryCount} ctx='ISO set' loading={t.countries.loading} updated={!!t.countries.ping} />
    </div>
  )
}

// ── ToolCard — one card per tool, auto-fires on mount ────────
//
// Each card owns its own input state, loading state, and last response. The
// parent staggers auto-fire kickoff via the `kickoffDelay` prop so the page
// doesn't fire 30 requests in the same tick.
function ToolCard({ tool, kickoffDelay }) {
  const seed = useMemo(() => {
    const def = TOOL_DEFAULTS[tool.name] || {}
    const out = {}
    for (const s of tool.paramSchema || []) {
      out[s.key] = def[s.key] ?? s.placeholder ?? ''
    }
    return out
  }, [tool])

  const [inputs, setInputs] = useState(seed)
  const [loading, setLoading] = useState(false)
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [lastStatus, setLastStatus] = useState(null)
  const fired = useRef(false)

  const buildUrl = (curInputs) => {
    const pathParts = (tool.paramSchema || []).filter((s) => s.source === 'path')
    const queryParts = (tool.paramSchema || []).filter((s) => s.source === 'query')
    const pathSeg = pathParts
      .map((s) => encodeURIComponent(String(curInputs[s.key] ?? '').trim()))
      .filter(Boolean)
      .join('/')
    const qs = new URLSearchParams()
    for (const s of queryParts) {
      const v = String(curInputs[s.key] ?? '').trim()
      if (v) qs.set(s.key, v)
    }
    return `/tool/${tool.name}${pathSeg ? '/' + pathSeg : ''}${qs.toString() ? '?' + qs.toString() : ''}`
  }

  const run = async (curInputs = inputs) => {
    // Validate required path params.
    const pathParts = (tool.paramSchema || []).filter((s) => s.source === 'path')
    for (const s of pathParts) {
      if (s.required && !String(curInputs[s.key] ?? '').trim()) {
        setError(`${s.label} is required`)
        setLastStatus('err')
        return
      }
    }
    setLoading(true); setError(null)
    try {
      const r = await osintGet(buildUrl(curInputs))
      setData(r?.data ?? r)
      setLastStatus('ok')
    } catch (e) {
      setError(e?.body?.error || e.message || 'failed')
      setLastStatus('err')
    } finally {
      setLoading(false)
    }
  }

  // Auto-fire once, staggered.
  useEffect(() => {
    if (fired.current) return
    fired.current = true
    const t = setTimeout(() => { run(seed) }, kickoffDelay)
    return () => clearTimeout(t)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const setInput = (k, v) => setInputs((s) => ({ ...s, [k]: v }))

  const Viz = pickViz(tool.name)

  const badge = lastStatus === 'ok'
    ? <Tooltip title='last run passed'><CheckCircleFilled className='text-emerald-400' /></Tooltip>
    : lastStatus === 'err'
      ? <Tooltip title='last run failed'><CloseCircleFilled className='text-rose-400' /></Tooltip>
      : !tool.configured
        ? <Tooltip title={`needs ${tool.needsKey}`}><ExclamationCircleFilled className='text-amber-400' /></Tooltip>
        : <Tooltip title='queued'><span className='inline-block w-2 h-2 rounded-full bg-gray-600' /></Tooltip>

  return (
    <div className='luxe-glass rounded-xl p-3 border border-white/[0.06] bg-white/[0.02] flex flex-col'>
      {/* Title row */}
      <div className='flex items-start gap-2 mb-2'>
        <ExperimentOutlined className='text-cyan-400 mt-0.5' />
        <div className='flex-1 min-w-0'>
          <div className='flex items-center gap-2 flex-wrap'>
            <span className='text-white font-bold text-xs font-mono'>{tool.name}</span>
            {badge}
            {tool.needsKey ? <Tag color='orange' className='!m-0 !text-[9px]'>key</Tag> : <Tag color='green' className='!m-0 !text-[9px]'>free</Tag>}
          </div>
          <p className='text-gray-400 text-[11px] leading-snug mt-0.5 line-clamp-2'>{tool.description}</p>
        </div>
      </div>

      {/* Inputs — inline, compact */}
      {(tool.paramSchema || []).length > 0 && (
        <div className='grid grid-cols-1 sm:grid-cols-2 gap-1.5 mb-2'>
          {tool.paramSchema.map((f) => (
            <div key={f.key}>
              <label className='text-[9px] uppercase tracking-widest text-gray-500 font-bold'>
                {f.label}{f.required && <span className='text-rose-400'> *</span>}
              </label>
              {f.type === 'number' ? (
                <InputNumber
                  size='small'
                  className='!w-full'
                  placeholder={f.placeholder}
                  value={inputs[f.key] ?? ''}
                  onChange={(v) => setInput(f.key, v ?? '')}
                />
              ) : (
                <Input
                  size='small'
                  placeholder={f.placeholder}
                  value={inputs[f.key] ?? ''}
                  onChange={(e) => setInput(f.key, e.target.value)}
                  onPressEnter={() => run()}
                />
              )}
              <div className='text-[9px] text-gray-500 mt-0.5 leading-snug line-clamp-1' title={f.helper}>{f.helper}</div>
            </div>
          ))}
        </div>
      )}

      {/* Actions */}
      <div className='flex items-center gap-2 mb-2'>
        <Button
          variant='primary'
          size='small'
          onClick={() => run()}
          disabled={loading}
          icon={loading ? null : <PlayCircleFilled />}
        >
          {loading ? 'Running…' : 'Re-run'}
        </Button>
        {!tool.configured && (
          <span className='text-[9px] text-amber-300 ml-auto'>
            env {tool.needsKey} not set
          </span>
        )}
      </div>

      {/* Result */}
      <div className='mt-1'>
        {loading ? (
          <div className='flex items-center gap-2 py-3'>
            <LuxeLoader variant='osint' size='sm' />
            <span className='text-[11px] text-gray-500'>Contacting upstream…</span>
          </div>
        ) : error ? (
          <div className='rounded-lg border border-rose-400/20 bg-rose-500/5 p-2 text-rose-200 text-xs'>
            {error}
          </div>
        ) : data != null ? (
          <Viz data={data} />
        ) : null}
      </div>
    </div>
  )
}

// ── Tool grid (auto-rendered from BE manifest) ──────────────
function ToolGrid({ manifest, q, filter }) {
  const filtered = useMemo(() => {
    if (!manifest) return []
    const needle = q.trim().toLowerCase()
    return manifest.filter((t) => {
      if (filter === 'keyless' && t.needsKey) return false
      if (filter === 'key' && !t.needsKey) return false
      if (!needle) return true
      return t.name.toLowerCase().includes(needle) || (t.description || '').toLowerCase().includes(needle)
    })
  }, [manifest, q, filter])

  if (filtered.length === 0) {
    return <div className='luxe-glass rounded-xl p-5'><Empty description={<span className='text-gray-500'>no tools match</span>} /></div>
  }

  return (
    <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3'>
      {filtered.map((t, idx) => (
        <ToolCard
          key={t.name}
          tool={t}
          kickoffDelay={KICKOFF_DELAY_MS + idx * STAGGER_MS}
        />
      ))}
    </div>
  )
}

// ── Full Catalog (search + Collapse per category) ───────────
const CATEGORY_ICONS = {
  'Username': '👤', 'Email Address': '📧', 'Domain Name': '🌐',
  'Cloud Infrastructure': '☁️', 'IP & MAC Address': '📡',
  'Images / Videos / Docs': '🖼️', 'Social Networks': '💬',
  'Instant Messaging': '💌', 'People Search Engines': '🔍',
  'Dating': '💘', 'Telephone Numbers': '📞', 'Public Records': '📜',
  'Compliance & Risk Intelligence': '⚖️', 'Business Records': '🏢',
  'Transportation': '✈️', 'Geolocation Tools / Maps': '🗺️',
  'Search Engines': '🔎', 'Online Communities': '👥', 'Archives': '🗄️',
  'Language Translation': '🈶', 'Mobile OSINT': '📱', 'Dark Web': '🌑',
  'Disinformation & Media Verification': '🎭',
  'Blockchain & Cryptocurrency': '₿', 'Classifieds': '📰',
  'Encoding / Decoding': '🔐', 'Tools': '🧰', 'AI Tools': '🤖',
  'Malicious File Analysis': '🦠', 'Cyber Threat Intelligence': '🛡️',
  'OpSec': '🕵️', 'Documentation / Evidence Capture': '📸', 'Training': '🎓',
}

const FullCatalog = () => {
  const [search, setSearch] = useState('')
  const [pricingFilter, setPricingFilter] = useState('all')
  const q = search.trim().toLowerCase()

  const filteredCats = useMemo(() => {
    return catalog.categories
      .map((cat) => {
        const apis = cat.apis.filter((a) => {
          if (pricingFilter === 'free' && a.pricing !== 'free') return false
          if (pricingFilter === 'paid' && a.pricing !== 'paid') return false
          if (pricingFilter === 'freemium' && !/freemium/.test(a.pricing)) return false
          if (!q) return true
          return (
            (a.name || '').toLowerCase().includes(q)
            || (a.description || '').toLowerCase().includes(q)
            || (a.bestFor || '').toLowerCase().includes(q)
            || (cat.name || '').toLowerCase().includes(q)
          )
        })
        return { ...cat, apis }
      })
      .filter((cat) => cat.apis.length > 0)
  }, [q, pricingFilter])

  const totalShown = filteredCats.reduce((n, c) => n + c.apis.length, 0)

  const collapseItems = filteredCats.map((cat) => ({
    key: cat.name,
    label: (
      <div className='flex items-center gap-2 min-w-0'>
        <span className='text-lg'>{CATEGORY_ICONS[cat.name] || '📂'}</span>
        <span className='text-white text-sm font-bold line-clamp-2 leading-tight'>{cat.name}</span>
        <Badge count={cat.apis.length} style={{ backgroundColor: 'rgba(251,191,36,0.2)', color: '#fbbf24', boxShadow: 'none' }} />
      </div>
    ),
    children: (
      <div className='overflow-x-auto -mx-3'>
        <table className='w-full min-w-[560px] text-xs'>
          <thead>
            <tr className='text-left text-gray-500 border-b border-white/5'>
              <th className='px-3 py-2 font-medium w-1/4'>Name</th>
              <th className='px-3 py-2 font-medium'>Description</th>
              <th className='px-3 py-2 font-medium w-20'>Pricing</th>
              <th className='px-3 py-2 font-medium w-14 text-right'>Link</th>
            </tr>
          </thead>
          <tbody>
            {cat.apis.map((a, i) => (
              <tr key={`${a.name}-${i}`} className='border-b border-white/[0.03] hover:bg-white/[0.02] transition-colors'>
                <td className='px-3 py-2 align-top'>
                  <div className='text-white font-medium'>{a.name}</div>
                  {a.categoryPath?.[1] && <div className='text-[10px] text-gray-500 mt-0.5'>{a.categoryPath[1]}</div>}
                </td>
                <td className='px-3 py-2 align-top text-gray-400'>
                  <div className='line-clamp-2'>{a.description || a.bestFor || '—'}</div>
                </td>
                <td className='px-3 py-2 align-top'>
                  <PricingTag pricing={a.pricing} />
                  {a.api && <div className='mt-1'><Tag color='blue'>API</Tag></div>}
                </td>
                <td className='px-3 py-2 align-top text-right'>
                  {a.url && (
                    <Tooltip title={a.url}>
                      <a
                        href={a.url} target='_blank' rel='noopener noreferrer'
                        className='inline-flex items-center gap-1 text-cyan-300 hover:text-cyan-200'
                        aria-label={`Open ${a.name}`}
                      >
                        <LinkOutlined />
                      </a>
                    </Tooltip>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    ),
  }))

  return (
    <div className='luxe-glass rounded-2xl p-4'>
      <div className='flex flex-col sm:flex-row sm:items-start gap-3 mb-3'>
        <div className='flex-1'>
          <Input
            allowClear
            size='middle'
            prefix={<SearchOutlined className='text-gray-500' />}
            placeholder={`Search ${catalog.stats.total} APIs across ${catalog.stats.categoriesCount} categories…`}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          <p className='text-[11px] text-fg-muted leading-snug mt-1'>
            Search across names, descriptions, and use cases.
          </p>
        </div>
        <div>
          <Segmented
            size='small'
            value={pricingFilter}
            onChange={setPricingFilter}
            options={[
              { label: 'All',      value: 'all' },
              { label: 'Free',     value: 'free' },
              { label: 'Freemium', value: 'freemium' },
              { label: 'Paid',     value: 'paid' },
            ]}
          />
          <p className='text-[11px] text-fg-muted leading-snug mt-1'>
            Free = no key or free tier available.
          </p>
        </div>
      </div>
      <div className='text-[10px] text-gray-500 mb-2'>
        showing {totalShown} of {catalog.stats.total} APIs in {filteredCats.length} categor{filteredCats.length === 1 ? 'y' : 'ies'}
      </div>
      <AnimatePresence mode='wait'>
        <motion.div
          key={`${q}::${pricingFilter}`}
          initial={{ opacity: 0, y: 4 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
        >
          {collapseItems.length === 0 ? (
            <Empty description={<span className='text-gray-500'>no APIs match your filters</span>} />
          ) : (
            <Collapse
              accordion={false}
              bordered={false}
              size='small'
              items={collapseItems}
              className='osint-collapse'
            />
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  )
}

// ── Coverage strip (compact, one row) ───────────────────────
const CoverageStrip = () => {
  const s = catalog.stats
  const freePct = Math.round(((s.free + s.freemium) / s.total) * 100)
  return (
    <div className='luxe-glass rounded-xl p-3 sm:p-4'>
      <div className='grid grid-cols-2 sm:grid-cols-5 gap-3 items-end'>
        <div>
          <div className='text-[10px] uppercase tracking-widest text-gray-500 font-bold'>Total APIs</div>
          <div className='text-white font-bold text-xl'>{s.total}</div>
        </div>
        <div>
          <div className='text-[10px] uppercase tracking-widest text-gray-500 font-bold'>Categories</div>
          <div className='text-white font-bold text-xl'>{s.categoriesCount}</div>
        </div>
        <div>
          <div className='text-[10px] uppercase tracking-widest text-gray-500 font-bold'>Free / freemium</div>
          <div className='text-emerald-300 font-bold text-xl'>{s.free + s.freemium}</div>
        </div>
        <div>
          <div className='text-[10px] uppercase tracking-widest text-gray-500 font-bold'>Paid</div>
          <div className='text-amber-300 font-bold text-xl'>{s.paid}</div>
        </div>
        <div className='col-span-2 sm:col-span-1'>
          <div className='text-[10px] uppercase tracking-widest text-gray-500 font-bold mb-0.5'>Free-tier coverage · {freePct}%</div>
          <Progress
            percent={freePct}
            showInfo={false}
            size='small'
            strokeColor={{ from: '#10b981', to: '#22d3ee' }}
            trailColor='rgba(255,255,255,0.05)'
          />
        </div>
      </div>
    </div>
  )
}

// ── Page shell ──────────────────────────────────────────────
export default function OsintHub() {
  const telemetry = useLiveTelemetry()
  const [manifest, setManifest] = useState(null)
  const [manifestErr, setManifestErr] = useState(null)
  const [q, setQ] = useState('')
  const [filter, setFilter] = useState('all')
  const [tab, setTab] = useState('tools')
  // Force a re-render every second so the "updated Xs ago" label ticks up
  // without touching real state. `tick` is intentionally read-only — the
  // setter is the whole point.
  const [, setTick] = useState(0)
  useEffect(() => {
    const t = setInterval(() => setTick((n) => n + 1), 1000)
    return () => clearInterval(t)
  }, [])

  useEffect(() => {
    osintGet('/tools')
      .then((r) => setManifest(r.tools || []))
      .catch((e) => setManifestErr(e.message || 'failed to load tools'))
  }, [])

  const total = manifest?.length ?? 0
  const configured = manifest?.filter((t) => t.configured).length ?? 0
  const keyless = manifest?.filter((t) => !t.needsKey).length ?? 0
  const ageSeconds = telemetry.lastUpdate ? Math.max(0, Math.round((Date.now() - telemetry.lastUpdate) / 1000)) : null

  return (
    <div className='min-h-screen bg-gray-950 text-white pt-20 pb-16'>
      <div className='max-w-6xl mx-auto px-4 sm:px-6 space-y-4'>

        {/* ── Compact hero + telemetry ────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.3 }}
        >
          <div className='luxe-glass rounded-2xl p-4 sm:p-5 relative overflow-hidden'>
            <div aria-hidden className='ambient-orb -top-24 -left-16 opacity-30' />
            <div aria-hidden className='ambient-orb ambient-orb-cool -bottom-24 -right-16 opacity-20' />
            <div className='flex flex-col md:flex-row md:items-center gap-3 mb-3'>
              <div className='flex-1'>
                <div className='flex items-center gap-2 mb-1'>
                  <span className='inline-block h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.9)] animate-pulse' />
                  <span className='text-[10px] uppercase tracking-widest text-gray-500 font-bold font-mono'>
                    {total || catalog.stats.total} tools · 6 live feeds · {ageSeconds != null ? `updated ${ageSeconds}s ago` : 'connecting…'}
                  </span>
                </div>
                <h1 className='font-poppins font-black text-2xl sm:text-4xl leading-tight'>
                  <span className='gradient-text-amber'>OSINT Powerhouse</span>
                </h1>
                <p className='text-gray-400 mt-1 text-xs sm:text-sm max-w-2xl'>
                  {catalog.stats.total}+ intel APIs · 32 auto-fired live tools · every response through a custom visualisation. All CORS-proxied.
                </p>
              </div>
              <div className='flex flex-wrap items-center gap-1.5 shrink-0'>
                <Tag icon={<SafetyCertificateFilled />} color='green'>proxied</Tag>
                <Tag icon={<ThunderboltFilled />} color='gold'>live</Tag>
                <Tag icon={<ApiOutlined />} color='cyan'>{keyless} keyless</Tag>
              </div>
            </div>
            <TelemetryStrip telemetry={telemetry} />
          </div>
        </motion.div>

        {/* ── Sticky filter bar + Tabs ─────────────────────── */}
        <div className='sticky top-16 z-20 -mx-4 sm:mx-0'>
          <div className='luxe-glass mx-4 sm:mx-0 rounded-xl p-2 sm:p-3 backdrop-blur-xl border border-white/[0.06]'>
            <Tabs
              activeKey={tab}
              onChange={setTab}
              size='small'
              className='osint-tabs'
              tabBarExtraContent={
                <div className='hidden md:flex items-center gap-2'>
                  <Input
                    allowClear
                    size='small'
                    style={{ width: 240 }}
                    prefix={<SearchOutlined className='text-gray-500' />}
                    placeholder={total ? `Search ${total} tools…` : 'Loading tools…'}
                    value={q}
                    onChange={(e) => setQ(e.target.value)}
                  />
                  <Segmented
                    size='small'
                    value={filter}
                    onChange={setFilter}
                    options={[
                      { label: 'All', value: 'all' },
                      { label: 'Keyless', value: 'keyless' },
                      { label: 'Key', value: 'key' },
                    ]}
                  />
                </div>
              }
              items={[
                { key: 'live', label: 'Live' },
                { key: 'tools', label: `Tools · ${total || '…'}` },
                { key: 'catalog', label: `Catalog · ${catalog.stats.total}` },
              ]}
            />
            {/* Mobile: search below tabs */}
            <div className='md:hidden mt-2 flex flex-col gap-2'>
              <Input
                allowClear
                size='small'
                prefix={<SearchOutlined className='text-gray-500' />}
                placeholder={total ? `Search ${total} tools…` : 'Loading tools…'}
                value={q}
                onChange={(e) => setQ(e.target.value)}
              />
              <Segmented
                size='small'
                block
                value={filter}
                onChange={setFilter}
                options={[
                  { label: 'All', value: 'all' },
                  { label: 'Keyless', value: 'keyless' },
                  { label: 'Key-only', value: 'key' },
                ]}
              />
            </div>
          </div>
        </div>

        {/* ── Tab content ──────────────────────────────────── */}
        {tab === 'live' && (
          <div className='space-y-3'>
            <CoverageStrip />
            <div className='luxe-glass rounded-xl p-4 text-xs text-gray-400 leading-relaxed'>
              <div className='text-[10px] uppercase tracking-widest text-gray-500 font-bold mb-1'>What's on this page</div>
              Six live feeds refresh every 30 seconds (top strip). The <span className='text-white font-bold'>Tools</span> tab auto-fires every tool card 800ms after mount so results are ready as you scroll — click <span className='text-white font-bold'>Re-run</span> to re-execute with edited inputs. The <span className='text-white font-bold'>Catalog</span> tab lists the {catalog.stats.total}-entry OSINT Framework directory, searchable.
            </div>
          </div>
        )}

        {tab === 'tools' && (
          <div>
            {manifestErr ? (
              <div className='luxe-glass rounded-xl p-5 text-rose-300 text-sm'>Could not load tool manifest — {manifestErr}</div>
            ) : !manifest ? (
              <div className='luxe-glass rounded-xl p-8 flex flex-col items-center'>
                <LuxeLoader variant='osint' size='md' label='Loading tool registry…' />
              </div>
            ) : (
              <ToolGrid manifest={manifest} q={q} filter={filter} />
            )}
          </div>
        )}

        {tab === 'catalog' && <FullCatalog />}

        <div className='text-center text-[10px] text-gray-600 pt-2'>
          Catalog synced {new Date(catalog.generatedAt).toLocaleDateString()} · <code className='text-gray-500'>scripts/sync-osint-catalog.js</code>
        </div>
      </div>

      {/* Style tweaks specific to this page. Kept inline so we don't
          scatter a one-off page's chrome across the global stylesheets. */}
      <style>{`
        .osint-collapse .ant-collapse-item {
          background: rgba(255,255,255,0.02);
          border: 1px solid rgba(255,255,255,0.06) !important;
          border-radius: 10px !important;
          margin-bottom: 8px;
          overflow: hidden;
        }
        .osint-collapse .ant-collapse-header {
          padding: 10px 12px !important;
        }
        .osint-collapse .ant-collapse-content-box {
          padding: 4px 8px 8px !important;
        }
        .osint-tabs .ant-tabs-nav {
          margin-bottom: 0 !important;
        }
        .osint-tabs .ant-tabs-tab {
          padding: 4px 12px !important;
          font-weight: 600;
        }
      `}</style>
    </div>
  )
}
