// OSINT Powerhouse — 150+ open-source intel APIs at your fingertips.
//
// Composition:
//   1. Hero               (title + tagline in luxe-glass)
//   2. Live telemetry     (6 cards polling the BE every 30 s)
//   3. Interactive tools  (5 panels: IP · Name · DNS · CVE · HN Live)
//   4. Full catalog       (1000+ APIs from src/constants/osintCatalog.json,
//                          rendered as searchable antd Collapse per-category)
//   5. Coverage stats     (totals + % free progress bar)
//
// The catalog JSON is generated by `scripts/sync-osint-catalog.js` — re-run
// that whenever E:/Siddharth/osint/framework.json changes.

import { useEffect, useMemo, useState, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  Collapse, Input, Tag, Skeleton, Statistic, Segmented, Progress, Empty,
  Tooltip, Badge, message,
} from 'antd'
import {
  ThunderboltFilled, FireFilled, RocketFilled, GlobalOutlined,
  AlertOutlined, TeamOutlined, SearchOutlined, LinkOutlined,
  SafetyCertificateFilled, UserOutlined, ApiOutlined, BugOutlined,
  ReadOutlined, ReloadOutlined, ArrowRightOutlined,
} from '@ant-design/icons'

import catalog from '../constants/osintCatalog.json'

// ── BE URL helper ─────────────────────────────────────────────
// Not going through src/api/request.js because those helpers throw on any
// non-2xx — but individual OSINT endpoints (breach without HIBP key,
// domain without Host.io key) legitimately return 501 and we want to show
// a graceful "not configured" state instead of a red toast.
const BE_URL = import.meta.env.VITE_BE_URL || 'http://localhost:4001'

async function osintGet(path) {
  const res = await fetch(`${BE_URL}/api/osint${path}`, {
    headers: { Accept: 'application/json' },
  })
  const ct = res.headers.get('content-type') || ''
  const body = ct.includes('application/json') ? await res.json().catch(() => null) : null
  if (!res.ok) {
    const err = new Error(body?.error || `HTTP ${res.status}`)
    err.status = res.status
    err.body = body
    throw err
  }
  return body
}

// Public Firebase HN API for per-item details (not proxied — endpoint is
// public, CORS-friendly and doesn't count toward any quota).
async function hnItem(id) {
  const res = await fetch(`https://hacker-news.firebaseio.com/v0/item/${id}.json`)
  if (!res.ok) throw new Error('hn item failed')
  return res.json()
}

// ── UI atoms ─────────────────────────────────────────────────
const StatCard = ({ icon, label, value, ctx, tone = 'amber', loading, updated }) => {
  const toneMap = {
    amber   : 'from-amber-400/25 to-rose-500/10 border-amber-400/25 text-amber-300',
    rose    : 'from-rose-500/25 to-fuchsia-500/10 border-rose-500/25 text-rose-300',
    fuchsia : 'from-fuchsia-500/25 to-violet-500/10 border-fuchsia-500/25 text-fuchsia-300',
    violet  : 'from-violet-500/25 to-indigo-500/10 border-violet-500/25 text-violet-300',
    cyan    : 'from-cyan-500/25 to-sky-500/10 border-cyan-500/25 text-cyan-300',
    emerald : 'from-emerald-500/25 to-teal-500/10 border-emerald-500/25 text-emerald-300',
  }
  return (
    <div className={`luxe-glass relative overflow-hidden border rounded-xl p-3 sm:p-4 bg-gradient-to-br ${toneMap[tone]}`}>
      <div className="flex items-center gap-2 mb-1">
        <span className="opacity-90">{icon}</span>
        <span className="text-[10px] uppercase tracking-widest text-gray-400 font-semibold">{label}</span>
      </div>
      {loading ? (
        <Skeleton.Input active size="small" style={{ width: '90%' }} />
      ) : (
        <motion.div
          key={String(value)}
          initial={{ opacity: 0, y: 6, scale: 0.98 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          transition={{ duration: 0.35 }}
          className="text-white font-bold text-lg sm:text-2xl leading-tight"
        >
          {value}
        </motion.div>
      )}
      {ctx && <div className="text-[10px] text-gray-400 mt-1 leading-snug line-clamp-2">{ctx}</div>}
      {updated && (
        <div className="absolute top-1.5 right-2 h-1.5 w-1.5 rounded-full bg-emerald-400 shadow-[0_0_6px_rgba(52,211,153,0.9)]" />
      )}
    </div>
  )
}

const PricingTag = ({ pricing }) => {
  const p = (pricing || 'unknown').toLowerCase()
  if (p === 'free') return <Tag color="green">FREE</Tag>
  if (p === 'freemium' || p === 'free/freemium') return <Tag color="cyan">FREEMIUM</Tag>
  if (p === 'paid') return <Tag color="orange">PAID</Tag>
  return <Tag color="default">?</Tag>
}

const SectionTitle = ({ eyebrow, title, sub }) => (
  <div className="mb-4 sm:mb-5">
    <div className="eyebrow-mono text-xs tracking-widest text-gray-500 mb-1">{eyebrow}</div>
    <h2 className="text-white font-bold text-xl sm:text-2xl">{title}</h2>
    {sub && <p className="text-gray-400 text-xs sm:text-sm mt-1 max-w-2xl">{sub}</p>}
  </div>
)

// ── Live telemetry (6 widgets, polling every 30 s) ──────────
function useLiveTelemetry() {
  const [state, setState] = useState({
    eq   : { loading: true, data: null, ping: 0 },
    fires: { loading: true, data: null, ping: 0 },
    iss  : { loading: true, data: null, ping: 0 },
    astros:{ loading: true, data: null, ping: 0 },
    alerts:{ loading: true, data: null, ping: 0 },
  })
  const [countries, setCountries] = useState({ loading: true, data: null, ping: 0 })

  const load = async () => {
    // Fire all five hot widgets in parallel. Any single failure just leaves
    // that slot showing its last known value; nothing bubbles up.
    const now = () => Date.now()
    const [eq, fires, iss, astros, alerts] = await Promise.allSettled([
      osintGet('/earthquakes?window=hour'),
      osintGet('/eonet?days=10&limit=200'),
      osintGet('/iss'),
      osintGet('/astros'),
      osintGet('/weather-alerts'),
    ])
    setState((s) => ({
      eq    : eq.status     === 'fulfilled' ? { loading: false, data: eq.value,     ping: now() } : { ...s.eq,     loading: false },
      fires : fires.status  === 'fulfilled' ? { loading: false, data: fires.value,  ping: now() } : { ...s.fires,  loading: false },
      iss   : iss.status    === 'fulfilled' ? { loading: false, data: iss.value,    ping: now() } : { ...s.iss,    loading: false },
      astros: astros.status === 'fulfilled' ? { loading: false, data: astros.value, ping: now() } : { ...s.astros, loading: false },
      alerts: alerts.status === 'fulfilled' ? { loading: false, data: alerts.value, ping: now() } : { ...s.alerts, loading: false },
    }))
  }

  useEffect(() => {
    load()
    const t = setInterval(load, 30_000)
    return () => clearInterval(t)
  }, [])

  // Countries — refresh only once per session; the payload is huge and
  // cached 24 h on the BE.
  useEffect(() => {
    osintGet('/countries')
      .then((data) => setCountries({ loading: false, data, ping: Date.now() }))
      .catch(() => setCountries((c) => ({ ...c, loading: false })))
  }, [])

  return { ...state, countries }
}

const TelemetryStrip = () => {
  const t = useLiveTelemetry()

  // Earthquakes: hourly USGS feed. Extract count + max magnitude.
  const eqCount = t.eq.data?.features?.length ?? 0
  const eqMax = t.eq.data?.features?.reduce(
    (m, f) => Math.max(m, f.properties?.mag ?? 0), 0
  )

  // EONET: active open events. Count filtered to wildfires only.
  const eonetEvents = t.fires.data?.events ?? []
  const wildfireCount = eonetEvents.filter((e) => (e.categories || []).some((c) => /fire/i.test(c.title))).length

  // ISS current position.
  const iss = t.iss.data?.iss_position
  const issTxt = iss ? `${(+iss.latitude).toFixed(2)}°, ${(+iss.longitude).toFixed(2)}°` : '—'

  // Astros in space.
  const astros = t.astros.data?.number ?? 0
  const craftSet = new Set((t.astros.data?.people ?? []).map(p => p.craft))
  const craftList = [...craftSet].join(' · ')

  // NOAA active weather alerts (US).
  const alertCount = t.alerts.data?.features?.length ?? 0

  // Countries.
  const countryCount = t.countries.data?.length ?? 0

  return (
    <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2 sm:gap-3">
      <StatCard
        icon={<ThunderboltFilled />} tone="amber"
        label="Earthquakes / hr"
        value={t.eq.loading ? '' : eqCount}
        ctx={eqCount ? `max mag ${eqMax?.toFixed(1)}` : 'last hour · USGS'}
        loading={t.eq.loading}
        updated={!!t.eq.ping}
      />
      <StatCard
        icon={<FireFilled />} tone="rose"
        label="Wildfires open"
        value={t.fires.loading ? '' : wildfireCount}
        ctx="NASA EONET · 10-day window"
        loading={t.fires.loading}
        updated={!!t.fires.ping}
      />
      <StatCard
        icon={<RocketFilled />} tone="cyan"
        label="ISS position"
        value={t.iss.loading ? '' : issTxt}
        ctx="live lat / lng · open-notify"
        loading={t.iss.loading}
        updated={!!t.iss.ping}
      />
      <StatCard
        icon={<UserOutlined />} tone="violet"
        label="Astros in space"
        value={t.astros.loading ? '' : astros}
        ctx={craftList || 'currently orbiting'}
        loading={t.astros.loading}
        updated={!!t.astros.ping}
      />
      <StatCard
        icon={<AlertOutlined />} tone="fuchsia"
        label="US weather alerts"
        value={t.alerts.loading ? '' : alertCount}
        ctx="NOAA active advisories"
        loading={t.alerts.loading}
        updated={!!t.alerts.ping}
      />
      <StatCard
        icon={<GlobalOutlined />} tone="emerald"
        label="Countries indexed"
        value={t.countries.loading ? '' : countryCount}
        ctx="REST Countries · full ISO set"
        loading={t.countries.loading}
        updated={!!t.countries.ping}
      />
    </div>
  )
}

// ── Panel: IP Lookup ────────────────────────────────────────
// Renders a tiny SVG world map with an amber dot at the (lat, lng) returned
// by ip-api. Country / org / ISP shown as a compact key-value grid.
const WorldMapDot = ({ lat, lng }) => {
  // Equirectangular projection: world map baked into 720×360 viewBox. The
  // outline is a stylised low-poly world silhouette — good enough for
  // "roughly where in the world is this IP" without shipping a topojson.
  const x = ((lng + 180) / 360) * 720
  const y = ((90 - lat) / 180) * 360
  return (
    <svg viewBox="0 0 720 360" className="w-full h-auto" aria-hidden>
      <defs>
        <radialGradient id="dotGlow">
          <stop offset="0%"  stopColor="#fbbf24" stopOpacity="1" />
          <stop offset="60%" stopColor="#fb7185" stopOpacity="0.4" />
          <stop offset="100%" stopColor="#fb7185" stopOpacity="0" />
        </radialGradient>
      </defs>
      <rect width="720" height="360" fill="rgba(255,255,255,0.02)" rx="12" />
      {/* Latitude grid lines */}
      {[60, 120, 180, 240, 300].map((y) => (
        <line key={y} x1="0" y1={y} x2="720" y2={y} stroke="rgba(255,255,255,0.05)" strokeWidth="0.5" />
      ))}
      {[120, 240, 360, 480, 600].map((x) => (
        <line key={x} x1={x} y1="0" x2={x} y2="360" stroke="rgba(255,255,255,0.05)" strokeWidth="0.5" />
      ))}
      {/* Continent silhouettes — hand-simplified polygons. Purely decorative. */}
      <g fill="rgba(148,163,184,0.18)" stroke="rgba(148,163,184,0.35)" strokeWidth="0.5">
        {/* North America */}
        <path d="M85 70 L200 60 L245 100 L235 155 L185 195 L145 205 L110 175 L80 130 Z" />
        {/* South America */}
        <path d="M195 205 L235 215 L250 260 L235 320 L205 335 L185 300 L180 250 Z" />
        {/* Europe */}
        <path d="M340 70 L400 65 L410 95 L390 120 L360 115 L335 100 Z" />
        {/* Africa */}
        <path d="M360 130 L420 130 L440 180 L430 245 L400 280 L370 260 L355 200 Z" />
        {/* Asia */}
        <path d="M420 60 L590 70 L620 120 L605 175 L555 190 L490 175 L430 145 L415 100 Z" />
        {/* Australia */}
        <path d="M555 235 L625 235 L640 275 L610 295 L560 285 Z" />
      </g>
      {Number.isFinite(lat) && Number.isFinite(lng) && (
        <>
          <circle cx={x} cy={y} r="18" fill="url(#dotGlow)" />
          <circle cx={x} cy={y} r="4" fill="#fbbf24" stroke="#fff" strokeWidth="1" />
        </>
      )}
    </svg>
  )
}

const IPPanel = () => {
  const [ip, setIp] = useState('8.8.8.8')
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(false)
  const [err, setErr] = useState(null)

  const run = async (val) => {
    const query = (val ?? ip).trim()
    if (!query) return
    setLoading(true); setErr(null); setData(null)
    try {
      const r = await osintGet(`/ip/${encodeURIComponent(query)}`)
      if (r?.status === 'fail') throw new Error(r.message || 'lookup failed')
      setData(r)
    } catch (e) {
      setErr(e.message || 'lookup failed')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { run('8.8.8.8') /* preload */ }, []) // eslint-disable-line

  return (
    <div className="luxe-glass rounded-2xl p-4 sm:p-5">
      <div className="flex items-center gap-2 mb-3">
        <GlobalOutlined className="text-cyan-400" />
        <span className="text-white font-semibold text-sm">IP Lookup</span>
        <span className="text-[10px] uppercase tracking-widest text-gray-500 ml-auto">ip-api</span>
      </div>
      <Input.Search
        value={ip} onChange={(e) => setIp(e.target.value)}
        placeholder="e.g. 8.8.8.8"
        enterButton={<span>Trace <ArrowRightOutlined /></span>}
        onSearch={() => run()}
        loading={loading}
      />
      <div className="mt-3 grid grid-cols-1 md:grid-cols-2 gap-3">
        <div>
          {loading ? (
            <Skeleton active paragraph={{ rows: 4 }} />
          ) : err ? (
            <div className="text-rose-400 text-xs">{err}</div>
          ) : data ? (
            <div className="grid grid-cols-2 gap-x-3 gap-y-1.5 text-xs">
              <div className="text-gray-500">Country</div><div className="text-white">{data.country} <span className="text-gray-500">({data.countryCode})</span></div>
              <div className="text-gray-500">Region</div><div className="text-white">{data.regionName}</div>
              <div className="text-gray-500">City</div><div className="text-white">{data.city} <span className="text-gray-500">{data.zip}</span></div>
              <div className="text-gray-500">ISP</div><div className="text-white truncate" title={data.isp}>{data.isp}</div>
              <div className="text-gray-500">Org</div><div className="text-white truncate" title={data.org}>{data.org || '—'}</div>
              <div className="text-gray-500">AS</div><div className="text-white truncate" title={data.as}>{data.as}</div>
              <div className="text-gray-500">Coords</div><div className="text-white">{data.lat?.toFixed(3)}, {data.lon?.toFixed(3)}</div>
              <div className="text-gray-500">Timezone</div><div className="text-white">{data.timezone}</div>
            </div>
          ) : null}
        </div>
        <div className="rounded-lg overflow-hidden border border-white/5">
          <WorldMapDot lat={data?.lat} lng={data?.lon} />
        </div>
      </div>
    </div>
  )
}

// ── Panel: Name Predictor (Genderize + Agify + Nationalize) ──
const NamePanel = () => {
  const [name, setName] = useState('siddharth')
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(false)
  const [err, setErr] = useState(null)

  const run = async (val) => {
    const q = (val ?? name).trim()
    if (!q) return
    setLoading(true); setErr(null); setData(null)
    try {
      const r = await osintGet(`/name/${encodeURIComponent(q)}`)
      setData(r)
    } catch (e) { setErr(e.message || 'failed') }
    finally { setLoading(false) }
  }

  useEffect(() => { run('siddharth') /* preload */ }, []) // eslint-disable-line

  const genderPct = Math.round(((data?.gender?.probability || 0) * 100))
  const nations = (data?.nationality?.country || []).slice(0, 3)
  const topNat = nations[0]

  return (
    <div className="luxe-glass rounded-2xl p-4 sm:p-5">
      <div className="flex items-center gap-2 mb-3">
        <UserOutlined className="text-fuchsia-400" />
        <span className="text-white font-semibold text-sm">Name Predictor</span>
        <span className="text-[10px] uppercase tracking-widest text-gray-500 ml-auto">Genderize · Agify · Nationalize</span>
      </div>
      <Input.Search
        value={name} onChange={(e) => setName(e.target.value)}
        placeholder="e.g. Priya"
        enterButton="Predict"
        onSearch={() => run()}
        loading={loading}
      />
      <div className="mt-3">
        {loading ? (
          <Skeleton active paragraph={{ rows: 3 }} />
        ) : err ? (
          <div className="text-rose-400 text-xs">{err}</div>
        ) : data ? (
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
            {/* Gender */}
            <div className="rounded-lg border border-white/5 bg-white/[0.03] p-3">
              <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-1">Gender</div>
              <div className="text-white font-bold text-lg capitalize">{data.gender?.gender || '—'}</div>
              <Progress
                percent={genderPct}
                showInfo
                size="small"
                strokeColor={data.gender?.gender === 'male' ? '#38bdf8' : '#ec4899'}
              />
              <div className="text-gray-500 text-[10px] mt-1">based on {data.gender?.count?.toLocaleString?.() || '—'} samples</div>
            </div>
            {/* Age */}
            <div className="rounded-lg border border-white/5 bg-white/[0.03] p-3">
              <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-1">Predicted Age</div>
              <div className="text-white font-bold text-lg">{data.age?.age ?? '—'} <span className="text-xs text-gray-400 font-normal">years</span></div>
              <div className="mt-2 flex items-end gap-0.5 h-10">
                {[15, 25, 35, 45, 55, 65, 75].map((peak) => {
                  const targetAge = data.age?.age || 30
                  const dist = Math.abs(peak - targetAge)
                  const h = Math.max(4, 40 - dist * 1.2)
                  const active = Math.abs(peak - targetAge) < 6
                  return <div key={peak} className={`flex-1 rounded-t ${active ? 'bg-amber-400' : 'bg-white/15'}`} style={{ height: `${h}px` }} />
                })}
              </div>
              <div className="flex justify-between text-[9px] text-gray-500 mt-0.5">
                <span>15</span><span>35</span><span>55</span><span>75</span>
              </div>
            </div>
            {/* Nationalities */}
            <div className="rounded-lg border border-white/5 bg-white/[0.03] p-3">
              <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-1">Nationality</div>
              <div className="text-white font-bold text-lg">{topNat ? `${flagEmoji(topNat.country_id)} ${topNat.country_id}` : '—'}</div>
              <div className="mt-2 space-y-1">
                {nations.map((n) => (
                  <div key={n.country_id} className="flex items-center gap-2">
                    <span className="w-6 text-gray-400 text-[10px]">{flagEmoji(n.country_id)}</span>
                    <span className="w-8 text-gray-300 text-[10px]">{n.country_id}</span>
                    <div className="flex-1 h-1.5 bg-white/5 rounded overflow-hidden">
                      <div className="h-full bg-gradient-to-r from-amber-400 to-rose-500" style={{ width: `${Math.round(n.probability * 100)}%` }} />
                    </div>
                    <span className="w-8 text-right text-gray-400 text-[10px]">{Math.round(n.probability * 100)}%</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  )
}

// ISO country code → flag emoji.
function flagEmoji(code) {
  if (!code || code.length !== 2) return '🏳️'
  const A = 0x1F1E6
  const chars = code.toUpperCase().split('').map((c) => String.fromCodePoint(A + c.charCodeAt(0) - 65))
  return chars.join('')
}

// ── Panel: DNS Resolver ──────────────────────────────────────
// The BE currently only proxies A-record lookups (Cloudflare DoH type=A).
// AAAA / MX / TXT would require either extra BE endpoints or per-record-
// type query params — flagged as a known limitation in the panel footer.
const DNSPanel = () => {
  const [domain, setDomain] = useState('siddharthfulia.com')
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(false)
  const [err, setErr] = useState(null)

  const run = async (val) => {
    const q = (val ?? domain).trim().toLowerCase()
    if (!q) return
    setLoading(true); setErr(null); setData(null)
    try {
      const r = await osintGet(`/dns/${encodeURIComponent(q)}`)
      setData(r)
    } catch (e) { setErr(e.message || 'failed') }
    finally { setLoading(false) }
  }

  useEffect(() => { run('siddharthfulia.com') /* preload */ }, []) // eslint-disable-line

  const answers = data?.Answer || []
  const authority = data?.Authority || []

  return (
    <div className="luxe-glass rounded-2xl p-4 sm:p-5">
      <div className="flex items-center gap-2 mb-3">
        <ApiOutlined className="text-emerald-400" />
        <span className="text-white font-semibold text-sm">DNS Resolver</span>
        <span className="text-[10px] uppercase tracking-widest text-gray-500 ml-auto">Cloudflare DoH · A records</span>
      </div>
      <Input.Search
        value={domain} onChange={(e) => setDomain(e.target.value)}
        placeholder="e.g. google.com"
        enterButton="Resolve"
        onSearch={() => run()}
        loading={loading}
      />
      <div className="mt-3">
        {loading ? (
          <Skeleton active paragraph={{ rows: 3 }} />
        ) : err ? (
          <div className="text-rose-400 text-xs">{err}</div>
        ) : data ? (
          <Collapse
            size="small"
            ghost
            defaultActiveKey={['a']}
            items={[
              {
                key: 'a',
                label: <span className="text-white text-xs">A records <Badge count={answers.length} color="#22d3ee" style={{ marginLeft: 6 }} /></span>,
                children: answers.length === 0 ? (
                  <div className="text-gray-500 text-xs">no A records</div>
                ) : (
                  <div className="space-y-1">
                    {answers.map((a, i) => (
                      <div key={i} className="flex items-center justify-between text-xs bg-white/[0.02] rounded px-2 py-1.5">
                        <span className="font-mono text-emerald-300">{a.data}</span>
                        <span className="text-gray-500">TTL {a.TTL}s</span>
                      </div>
                    ))}
                  </div>
                ),
              },
              {
                key: 'authority',
                label: <span className="text-white text-xs">Authority <Badge count={authority.length} color="#6366f1" style={{ marginLeft: 6 }} /></span>,
                children: authority.length === 0 ? (
                  <div className="text-gray-500 text-xs">no authority records</div>
                ) : (
                  <div className="space-y-1">
                    {authority.map((a, i) => (
                      <div key={i} className="text-xs font-mono text-gray-300 break-all">{a.data}</div>
                    ))}
                  </div>
                ),
              },
            ]}
          />
        ) : null}
        <div className="text-[10px] text-gray-500 mt-2">AAAA / MX / TXT lookups pending BE support — currently A-record only.</div>
      </div>
    </div>
  )
}

// ── Panel: CVE Lookup ────────────────────────────────────────
const CVEPanel = () => {
  const [cve, setCve] = useState('CVE-2021-44228')      // log4shell as the demo
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(false)
  const [err, setErr] = useState(null)

  const run = async (val) => {
    const q = (val ?? cve).trim().toUpperCase()
    if (!/^CVE-\d{4}-\d{4,}$/.test(q)) { setErr('format: CVE-YYYY-NNNN'); return }
    setLoading(true); setErr(null); setData(null)
    try {
      const r = await osintGet(`/cve/${encodeURIComponent(q)}`)
      setData(r)
    } catch (e) { setErr(e.message || 'failed') }
    finally { setLoading(false) }
  }

  useEffect(() => { run('CVE-2021-44228') /* preload */ }, []) // eslint-disable-line

  const cveObj = data?.vulnerabilities?.[0]?.cve
  const desc = cveObj?.descriptions?.find((d) => d.lang === 'en')?.value
  const metrics = cveObj?.metrics
  // Prefer CVSS v3.1 → v3 → v2 → nothing.
  const cvss = metrics?.cvssMetricV31?.[0]?.cvssData
    || metrics?.cvssMetricV30?.[0]?.cvssData
    || metrics?.cvssMetricV2?.[0]?.cvssData
  const severity = (metrics?.cvssMetricV31?.[0]?.baseSeverity
    || metrics?.cvssMetricV30?.[0]?.baseSeverity
    || metrics?.cvssMetricV2?.[0]?.baseSeverity
    || 'UNKNOWN').toUpperCase()
  const refs = (cveObj?.references || []).slice(0, 4)

  const sevColor = {
    CRITICAL: 'red',
    HIGH    : 'volcano',
    MEDIUM  : 'gold',
    LOW     : 'green',
    UNKNOWN : 'default',
  }[severity]

  return (
    <div className="luxe-glass rounded-2xl p-4 sm:p-5">
      <div className="flex items-center gap-2 mb-3">
        <BugOutlined className="text-rose-400" />
        <span className="text-white font-semibold text-sm">CVE Lookup</span>
        <span className="text-[10px] uppercase tracking-widest text-gray-500 ml-auto">NIST NVD</span>
      </div>
      <Input.Search
        value={cve} onChange={(e) => setCve(e.target.value.toUpperCase())}
        placeholder="CVE-YYYY-NNNN"
        enterButton="Look up"
        onSearch={() => run()}
        loading={loading}
      />
      <div className="mt-3">
        {loading ? (
          <Skeleton active paragraph={{ rows: 4 }} />
        ) : err ? (
          <div className="text-rose-400 text-xs">{err}</div>
        ) : cveObj ? (
          <div className="space-y-3">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-white font-mono text-sm">{cveObj.id}</span>
              <Tag color={sevColor}>{severity}</Tag>
              {cvss?.baseScore != null && <Tag color="magenta">CVSS {cvss.baseScore}</Tag>}
              {cvss?.attackVector && <Tag>AV: {cvss.attackVector}</Tag>}
            </div>
            <p className="text-gray-300 text-xs leading-relaxed line-clamp-5">{desc || '—'}</p>
            {refs.length > 0 && (
              <div>
                <div className="text-[10px] uppercase tracking-widest text-gray-500 mb-1">References</div>
                <div className="space-y-1">
                  {refs.map((r, i) => (
                    <a
                      key={i} href={r.url} target="_blank" rel="noopener noreferrer"
                      className="block text-cyan-300 hover:text-cyan-200 text-xs truncate"
                    >{r.url}</a>
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : null}
      </div>
    </div>
  )
}

// ── Panel: HackerNews Live ───────────────────────────────────
const HNPanel = () => {
  const [type, setType] = useState('topstories')
  const [items, setItems] = useState([])
  const [loading, setLoading] = useState(false)
  const [err, setErr] = useState(null)

  const load = async (t) => {
    setLoading(true); setErr(null)
    try {
      const ids = await osintGet(`/hackernews/${t}`)
      const top = (ids || []).slice(0, 10)
      // Fan out per-item fetches to the public HN Firebase endpoint. Any
      // individual failure just yields null and gets filtered out.
      const details = await Promise.all(top.map((id) => hnItem(id).catch(() => null)))
      setItems(details.filter(Boolean))
    } catch (e) { setErr(e.message || 'failed') }
    finally { setLoading(false) }
  }

  useEffect(() => { load(type) }, [type])

  return (
    <div className="luxe-glass rounded-2xl p-4 sm:p-5">
      <div className="flex items-center gap-2 mb-3">
        <ReadOutlined className="text-amber-400" />
        <span className="text-white font-semibold text-sm">HackerNews Live</span>
        <div className="ml-auto">
          <Segmented
            size="small"
            value={type}
            onChange={setType}
            options={[
              { label: 'Top', value: 'topstories' },
              { label: 'New', value: 'newstories' },
              { label: 'Best', value: 'beststories' },
            ]}
          />
        </div>
      </div>
      {loading ? (
        <Skeleton active paragraph={{ rows: 6 }} />
      ) : err ? (
        <div className="text-rose-400 text-xs">{err}</div>
      ) : (
        <div className="space-y-1.5">
          {items.map((it, i) => (
            <a
              key={it.id} href={it.url || `https://news.ycombinator.com/item?id=${it.id}`}
              target="_blank" rel="noopener noreferrer"
              className="flex items-start gap-2 rounded-lg px-2 py-2 hover:bg-white/[0.04] transition-colors"
            >
              <span className="text-gray-500 font-mono text-xs w-5 text-right shrink-0 pt-0.5">{i + 1}</span>
              <div className="flex-1 min-w-0">
                <div className="text-white text-xs leading-snug line-clamp-2">{it.title}</div>
                <div className="text-gray-500 text-[10px] mt-0.5 flex items-center gap-2">
                  <span>{it.score ?? 0} pts</span>
                  <span>·</span>
                  <span>{it.descendants ?? 0} comments</span>
                  <span>·</span>
                  <span className="text-gray-600">{it.by}</span>
                </div>
              </div>
            </a>
          ))}
          {items.length === 0 && <Empty description={<span className="text-gray-500">no stories</span>} />}
        </div>
      )}
    </div>
  )
}

// ── Full Catalog (search + Collapse per category) ───────────
const CATEGORY_ICONS = {
  'Username'                       : '👤',
  'Email Address'                  : '📧',
  'Domain Name'                    : '🌐',
  'Cloud Infrastructure'           : '☁️',
  'IP & MAC Address'               : '📡',
  'Images / Videos / Docs'         : '🖼️',
  'Social Networks'                : '💬',
  'Instant Messaging'              : '💌',
  'People Search Engines'          : '🔍',
  'Dating'                         : '💘',
  'Telephone Numbers'              : '📞',
  'Public Records'                 : '📜',
  'Compliance & Risk Intelligence' : '⚖️',
  'Business Records'               : '🏢',
  'Transportation'                 : '✈️',
  'Geolocation Tools / Maps'       : '🗺️',
  'Search Engines'                 : '🔎',
  'Online Communities'             : '👥',
  'Archives'                       : '🗄️',
  'Language Translation'           : '🈶',
  'Mobile OSINT'                   : '📱',
  'Dark Web'                       : '🌑',
  'Disinformation & Media Verification': '🎭',
  'Blockchain & Cryptocurrency'    : '₿',
  'Classifieds'                    : '📰',
  'Encoding / Decoding'            : '🔐',
  'Tools'                          : '🧰',
  'AI Tools'                       : '🤖',
  'Malicious File Analysis'        : '🦠',
  'Cyber Threat Intelligence'      : '🛡️',
  'OpSec'                          : '🕵️',
  'Documentation / Evidence Capture': '📸',
  'Training'                       : '🎓',
}

const FullCatalog = () => {
  const [search, setSearch] = useState('')
  const [pricingFilter, setPricingFilter] = useState('all')
  const q = search.trim().toLowerCase()

  // Filter each category. Empty categories hide entirely so the accordion
  // stays tight while typing.
  const filteredCats = useMemo(() => {
    return catalog.categories
      .map((cat) => {
        const apis = cat.apis.filter((a) => {
          if (pricingFilter === 'free' && a.pricing !== 'free') return false
          if (pricingFilter === 'paid' && a.pricing !== 'paid') return false
          if (pricingFilter === 'freemium' && !/freemium/.test(a.pricing)) return false
          if (!q) return true
          return (
            (a.name || '').toLowerCase().includes(q)
            || (a.description || '').toLowerCase().includes(q)
            || (a.bestFor || '').toLowerCase().includes(q)
            || (cat.name || '').toLowerCase().includes(q)
          )
        })
        return { ...cat, apis }
      })
      .filter((cat) => cat.apis.length > 0)
  }, [q, pricingFilter])

  const totalShown = filteredCats.reduce((n, c) => n + c.apis.length, 0)

  const collapseItems = filteredCats.map((cat) => ({
    key: cat.name,
    label: (
      <div className="flex items-center gap-2 min-w-0">
        <span className="text-lg">{CATEGORY_ICONS[cat.name] || '📂'}</span>
        <span className="text-white text-sm font-semibold truncate">{cat.name}</span>
        <Badge count={cat.apis.length} style={{ backgroundColor: 'rgba(251,191,36,0.2)', color: '#fbbf24', boxShadow: 'none' }} />
      </div>
    ),
    children: (
      <div className="overflow-x-auto -mx-3">
        <table className="w-full min-w-[560px] text-xs">
          <thead>
            <tr className="text-left text-gray-500 border-b border-white/5">
              <th className="px-3 py-2 font-medium w-1/4">Name</th>
              <th className="px-3 py-2 font-medium">Description</th>
              <th className="px-3 py-2 font-medium w-20">Pricing</th>
              <th className="px-3 py-2 font-medium w-14 text-right">Link</th>
            </tr>
          </thead>
          <tbody>
            {cat.apis.map((a, i) => (
              <tr key={`${a.name}-${i}`} className="border-b border-white/[0.03] hover:bg-white/[0.02] transition-colors">
                <td className="px-3 py-2 align-top">
                  <div className="text-white font-medium">{a.name}</div>
                  {a.categoryPath?.[1] && <div className="text-[10px] text-gray-500 mt-0.5">{a.categoryPath[1]}</div>}
                </td>
                <td className="px-3 py-2 align-top text-gray-400">
                  <div className="line-clamp-2">{a.description || a.bestFor || '—'}</div>
                </td>
                <td className="px-3 py-2 align-top">
                  <PricingTag pricing={a.pricing} />
                  {a.api && <div className="mt-1"><Tag color="blue">API</Tag></div>}
                </td>
                <td className="px-3 py-2 align-top text-right">
                  {a.url && (
                    <Tooltip title={a.url}>
                      <a
                        href={a.url} target="_blank" rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-cyan-300 hover:text-cyan-200"
                        aria-label={`Open ${a.name}`}
                      >
                        <LinkOutlined />
                      </a>
                    </Tooltip>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    ),
  }))

  return (
    <div className="luxe-glass rounded-2xl p-4 sm:p-5">
      <div className="flex flex-col sm:flex-row sm:items-center gap-3 mb-4">
        <div className="flex-1">
          <Input
            allowClear
            size="middle"
            prefix={<SearchOutlined className="text-gray-500" />}
            placeholder={`Search ${catalog.stats.total} APIs across ${catalog.stats.categoriesCount} categories…`}
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <Segmented
          size="small"
          value={pricingFilter}
          onChange={setPricingFilter}
          options={[
            { label: 'All',      value: 'all' },
            { label: 'Free',     value: 'free' },
            { label: 'Freemium', value: 'freemium' },
            { label: 'Paid',     value: 'paid' },
          ]}
        />
      </div>
      <div className="text-[10px] text-gray-500 mb-2">
        showing {totalShown} of {catalog.stats.total} APIs in {filteredCats.length} categor{filteredCats.length === 1 ? 'y' : 'ies'}
      </div>
      <AnimatePresence mode="wait">
        <motion.div
          key={`${q}::${pricingFilter}`}
          initial={{ opacity: 0, y: 4 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
        >
          {collapseItems.length === 0 ? (
            <Empty description={<span className="text-gray-500">no APIs match your filters</span>} />
          ) : (
            <Collapse
              accordion={false}
              bordered={false}
              size="small"
              items={collapseItems}
              className="osint-collapse"
            />
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  )
}

// ── Coverage stats ──────────────────────────────────────────
const CoverageStrip = () => {
  const s = catalog.stats
  const freePct = Math.round(((s.free + s.freemium) / s.total) * 100)
  return (
    <div className="luxe-glass rounded-2xl p-4 sm:p-5">
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-3">
        <div>
          <div className="text-[10px] uppercase tracking-widest text-gray-500">Total APIs</div>
          <div className="text-white font-bold text-2xl">{s.total}</div>
        </div>
        <div>
          <div className="text-[10px] uppercase tracking-widest text-gray-500">Categories</div>
          <div className="text-white font-bold text-2xl">{s.categoriesCount}</div>
        </div>
        <div>
          <div className="text-[10px] uppercase tracking-widest text-gray-500">Free / Freemium</div>
          <div className="text-emerald-300 font-bold text-2xl">{s.free + s.freemium}</div>
        </div>
        <div>
          <div className="text-[10px] uppercase tracking-widest text-gray-500">Paid</div>
          <div className="text-amber-300 font-bold text-2xl">{s.paid}</div>
        </div>
      </div>
      <div>
        <div className="flex items-center justify-between text-[11px] text-gray-400 mb-1">
          <span>Free-tier coverage</span>
          <span className="text-emerald-300 font-semibold">{freePct}%</span>
        </div>
        <Progress
          percent={freePct}
          showInfo={false}
          strokeColor={{ from: '#10b981', to: '#22d3ee' }}
          trailColor="rgba(255,255,255,0.05)"
        />
        <div className="text-[10px] text-gray-500 mt-1">
          Free {s.free} · Freemium {s.freemium} · Paid {s.paid} · Unknown {s.unknown}
        </div>
      </div>
    </div>
  )
}

// ── Page shell ──────────────────────────────────────────────
export default function OsintHub() {
  return (
    <div className="min-h-screen bg-gray-950 text-white pt-24 pb-16">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 space-y-6 sm:space-y-8">

        {/* ── Hero ───────────────────────────────────────── */}
        <motion.div
          initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}
        >
          <div className="luxe-glass rounded-3xl p-5 sm:p-7 relative overflow-hidden">
            <div aria-hidden className="ambient-orb -top-24 -left-16 opacity-40" />
            <div aria-hidden className="ambient-orb ambient-orb-cool -bottom-24 -right-16 opacity-30" />
            <div className="eyebrow-mono text-xs tracking-widest text-gray-500 mb-2">
              // {catalog.stats.total} APIs · {catalog.stats.categoriesCount} categories · {catalog.stats.free + catalog.stats.freemium} free
            </div>
            <h1 className="font-poppins font-black text-3xl sm:text-5xl lg:text-6xl leading-tight">
              <span className="gradient-text-amber">OSINT Powerhouse</span>
            </h1>
            <p className="text-gray-400 mt-3 text-sm sm:text-base max-w-2xl">
              150+ open-source intel APIs at your fingertips. Free-tier data proxied through the BE for zero-config exploration. Paid ones catalogued so you know where to look.
            </p>
            <div className="mt-4 flex flex-wrap items-center gap-2">
              <Tag icon={<SafetyCertificateFilled />} color="green">CORS-safe proxy</Tag>
              <Tag icon={<ThunderboltFilled />} color="gold">Live telemetry</Tag>
              <Tag icon={<ApiOutlined />} color="cyan">17 BE endpoints</Tag>
              <Tag color="magenta">Mobile-friendly</Tag>
            </div>
          </div>
        </motion.div>

        {/* ── Live telemetry strip ───────────────────────── */}
        <section>
          <SectionTitle
            eyebrow="// live telemetry · 30 s refresh"
            title="Real-time signals"
            sub="Six always-on feeds proxied through the BE — earthquakes, wildfires, ISS, astros, weather alerts, and country reference."
          />
          <TelemetryStrip />
        </section>

        {/* ── Interactive tool panels ────────────────────── */}
        <section>
          <SectionTitle
            eyebrow="// interactive · zero-config"
            title="Try the tools"
            sub="Five live panels — punch in an IP, name, domain, CVE, or watch HackerNews stream. All data proxied through api.siddharthfulia.com."
          />
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 sm:gap-4">
            <IPPanel />
            <NamePanel />
            <DNSPanel />
            <CVEPanel />
            <div className="lg:col-span-2">
              <HNPanel />
            </div>
          </div>
        </section>

        {/* ── Coverage ───────────────────────────────────── */}
        <section>
          <SectionTitle
            eyebrow="// coverage"
            title="What the catalog tracks"
            sub="Every entry is scraped from the OSINT Framework tree with pricing, description, best-for, and OpSec metadata."
          />
          <CoverageStrip />
        </section>

        {/* ── Full catalog ───────────────────────────────── */}
        <section>
          <SectionTitle
            eyebrow="// full catalog · searchable"
            title={`All ${catalog.stats.total} APIs`}
            sub="Type to fuzzy-match across names, descriptions, and use cases. Free/paid filter narrows the shortlist."
          />
          <FullCatalog />
        </section>

        <div className="text-center text-[10px] text-gray-600 pt-4">
          Catalog synced {new Date(catalog.generatedAt).toLocaleDateString()} ·  <code className="text-gray-500">scripts/sync-osint-catalog.js</code>
        </div>
      </div>

      {/* Style tweaks specific to this page. Kept inline so we don't
          scatter a one-off page's chrome across the global stylesheets. */}
      <style>{`
        .osint-collapse .ant-collapse-item {
          background: rgba(255,255,255,0.02);
          border: 1px solid rgba(255,255,255,0.06) !important;
          border-radius: 10px !important;
          margin-bottom: 8px;
          overflow: hidden;
        }
        .osint-collapse .ant-collapse-header {
          padding: 10px 12px !important;
        }
        .osint-collapse .ant-collapse-content-box {
          padding: 4px 8px 8px !important;
        }
      `}</style>
    </div>
  )
}
