// /room — AI Room Designer. Upload a video sweep of a room, the
// pipeline pulls keyframes, runs object detection + depth + room
// layout estimation, sends the analysis to Groq for a critique
// ("what's missing", "what's empty"), surfaces a furniture catalog
// of suggestions, lets the user pick what to add, then composites
// the items back into the frames and exports an MP4.
//
// THIS PAGE IS THE V1 — FE flow + UX scaffold are wired end-to-end
// against a mock analysis. The BE + worker pipeline that actually
// produces real analysis + composited MP4 lands in a follow-up
// commit (it's a multi-step worker chain that needs its own session
// to build correctly). The "Status: simulated" pill makes the
// current state explicit so nobody mistakes the demo for production.
//
// Once the worker side is live, the only FE change is swapping the
// `useRoomAnalysis(videoFile)` stub for the real `/api/room/*`
// endpoints — the rest of this page stays.

import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  CloudUploadOutlined,
  PlayCircleOutlined,
  HomeOutlined,
  AppstoreOutlined,
  CheckOutlined,
  ReloadOutlined,
  DownloadOutlined,
  BulbOutlined,
  ExperimentOutlined,
  ShoppingOutlined,
  RocketOutlined,
  InfoCircleOutlined,
} from "@ant-design/icons";
import { uploadAndAnalyze, startRender, getRoomStatus, newRoomJobId } from "../api/room";

// ── Mock analysis — what the real worker chain will eventually return.
// Shape is intentional: keep parity with the planned `/api/room/analyze`
// response so swapping the data source is a one-liner.
const MOCK_ANALYSIS = {
  roomType: "Living room · ~3.4 m × 4.1 m",
  toneNotes: [
    "Warm, neutral palette · oak floor, off-white walls",
    "South-facing window — strong afternoon light",
    "No accent lighting · ceiling fixture is the only source",
  ],
  detected: [
    { label: "Sofa",         conf: 0.94, box: "right wall" },
    { label: "Coffee table", conf: 0.88, box: "center" },
    { label: "TV",           conf: 0.91, box: "left wall" },
    { label: "Rug",          conf: 0.71, box: "under coffee table" },
  ],
  missing: [
    { label: "Floor lamp",        why: "Single ceiling source · room goes flat after sunset" },
    { label: "Bookshelf or art",  why: "Right wall above sofa is bare · ~1.6 m of dead surface" },
    { label: "Side table",        why: "Sofa-end has nowhere for a drink or remote" },
    { label: "Plant",             why: "No biophilia · corners read sterile" },
  ],
  spaceGapPct: 22,
};

// Mock furniture catalog — V1 uses these. V2 swaps for a live catalog
// (IKEA / Wayfair RSS or a curated set generated by Flux + saved as
// product cards). Each card has an image URL, a tone tag, and a slot
// it best fits (so the recommendation engine can rank them).
const MOCK_CATALOG = [
  { id: "lamp-arc",   label: "Brass arc floor lamp",  slot: "Floor lamp",       tone: "warm",    price: "₹6,400",  img: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=70" },
  { id: "lamp-tri",   label: "Tripod floor lamp",     slot: "Floor lamp",       tone: "neutral", price: "₹4,200",  img: "https://images.unsplash.com/photo-1565374395542-0ce18882c857?auto=format&fit=crop&w=800&q=70" },
  { id: "shelf-oak",  label: "Oak ladder bookshelf",  slot: "Bookshelf or art", tone: "warm",    price: "₹11,900", img: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=800&q=70" },
  { id: "art-mono",   label: "Monochrome canvas set", slot: "Bookshelf or art", tone: "neutral", price: "₹3,800",  img: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=70" },
  { id: "side-walnut",label: "Walnut side table",     slot: "Side table",       tone: "warm",    price: "₹5,500",  img: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=800&q=70" },
  { id: "plant-fid",  label: "Fiddle-leaf fig (XL)",  slot: "Plant",            tone: "green",   price: "₹2,200",  img: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=800&q=70" },
];

export default function RoomDesign() {
  const navigate     = useNavigate();
  const videoRef     = useRef(null);
  const objUrlRef    = useRef(null);

  const [file, setFile]           = useState(null);
  const [previewUrl, setPreview]  = useState("");
  const [stage, setStage]         = useState("idle");
  // 'idle' | 'analyzing' | 'analyzed' | 'rendering' | 'done'
  const [analysis, setAnalysis]   = useState(null);
  const [picked, setPicked]       = useState(new Set());
  const [jobId, setJobId]         = useState(null);
  const [mp4Url, setMp4Url]       = useState(null);
  const [resumed, setResumed]     = useState(false);  // true if we re-attached
  const [logs, setLogs]           = useState([]);     // live job_logs tail
  const [errorMsg, setErrorMsg]   = useState(null);
  const pollRef                   = useRef(null);

  // Clean up object URL + any in-flight render poller on unmount.
  useEffect(() => () => {
    if (objUrlRef.current) URL.revokeObjectURL(objUrlRef.current);
    if (pollRef.current)   clearInterval(pollRef.current);
  }, []);

  // Resume on mount — if a previous session left a jobId in the URL
  // (`?j=room_...`) or localStorage, re-fetch its current state from
  // the BE and rehydrate the UI. Both analyze + render are persisted
  // server-side (room_jobs row), so closing the tab never loses work.
  // Loop:
  //   localStorage `sid-room-active-job` ← latest jobId
  //   URL `?j=jobId` ← shareable / refresh-safe handle
  // Either source wins; URL takes precedence so a deep link works.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const url = new URL(window.location.href);
        const urlJob = url.searchParams.get("j");
        const lsJob  = (typeof localStorage !== "undefined")
                     ? localStorage.getItem("sid-room-active-job")
                     : null;
        const id = urlJob || lsJob;
        if (!id) return;
        const row = await getRoomStatus(id);
        if (cancelled || !row) return;
        if (row.status === "failed") {
          setErrorMsg(row.error || "Previous render failed");
          return;
        }
        // Rehydrate whatever state we can. We don't have the source
        // file (browser can't recover it), but the analysis + result
        // are server-truth so the user picks up where they left off.
        setJobId(id);
        if (row.analysis) setAnalysis(row.analysis);
        if (row.pickedItems?.length) {
          setPicked(new Set(row.pickedItems.map((i) => i.id).filter(Boolean)));
        }
        if (Array.isArray(row.logs)) setLogs(row.logs);
        setResumed(true);

        if (row.status === "analyzing") {
          setStage("analyzing");
          beginAnalyzePoll(id);
        } else if (row.status === "rendering") {
          setStage("rendering");
          beginRenderPoll(id);
        } else if (row.status === "completed" && row.mp4Url) {
          setMp4Url(row.mp4Url);
          setStage("done");
        } else if (row.status === "analyzed") {
          setStage("analyzed");
        }
      } catch (_) {
        // Stale id is fine — drop it and let the user start fresh.
        try { localStorage.removeItem("sid-room-active-job"); } catch {}
      }
    })();
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Mirror the active jobId to URL + localStorage so any close /
  // refresh leaves a resume breadcrumb. Only writes when jobId is set
  // and a meaningful stage is in flight — clears on reset.
  useEffect(() => {
    try {
      const url = new URL(window.location.href);
      if (jobId && stage !== "idle") {
        url.searchParams.set("j", jobId);
        window.history.replaceState(null, "", url.toString());
        localStorage.setItem("sid-room-active-job", jobId);
      } else if (!jobId) {
        url.searchParams.delete("j");
        window.history.replaceState(null, "", url.toString());
        localStorage.removeItem("sid-room-active-job");
      }
    } catch {}
  }, [jobId, stage]);

  // Extracted so both runRender and the resume effect can use the
  // same polling logic.
  const beginRenderPoll = (id) => {
    const started = Date.now();
    const HARD_CEILING_MS = 12 * 60 * 1000;
    if (pollRef.current) clearInterval(pollRef.current);
    pollRef.current = setInterval(async () => {
      try {
        const row = await getRoomStatus(id);
        if (Array.isArray(row?.logs)) setLogs(row.logs);
        if (row?.status === "completed" && row.mp4Url) {
          clearInterval(pollRef.current);
          pollRef.current = null;
          setMp4Url(row.mp4Url);
          setStage("done");
        } else if (row?.status === "failed") {
          clearInterval(pollRef.current);
          pollRef.current = null;
          setErrorMsg(row.error || "Render failed on worker");
          setStage("analyzed");
        } else if (Date.now() - started > HARD_CEILING_MS) {
          clearInterval(pollRef.current);
          pollRef.current = null;
          setErrorMsg("Render timed out (>12 min)");
          setStage("analyzed");
        }
      } catch (_) { /* transient — keep polling */ }
    }, 4000);
  };

  const onPickFile = (f) => {
    if (!f) return;
    if (objUrlRef.current) URL.revokeObjectURL(objUrlRef.current);
    const url = URL.createObjectURL(f);
    objUrlRef.current = url;
    setFile(f);
    setPreview(url);
    setStage("idle");
    setAnalysis(null);
    setPicked(new Set());
  };

  const onDrop = (e) => {
    e.preventDefault();
    const f = e.dataTransfer?.files?.[0];
    if (f && f.type.startsWith("video/")) onPickFile(f);
  };

  // V2.0 — hit the real BE /api/room/analyze. The endpoint is
  // synchronous (~10-15s) so the request hangs until the analysis
  // JSON comes back. The UI shows "Reading the room…" the whole time.
  // The BE inserts the room_jobs row BEFORE running the pipeline, so
  // even if the user closes the tab mid-analyze the row is on disk
  // and the analysis completes server-side — the resume effect will
  // pick it up on the next visit.
  const runAnalysis = async () => {
    // Mint the jobId BEFORE the upload starts so the breadcrumb
    // effect persists it immediately. If the tab closes mid-upload,
    // the next visit can still re-attach via /status/:jobId.
    const newJob = newRoomJobId();
    setJobId(newJob);
    setStage("analyzing");
    setErrorMsg(null);
    setResumed(false);
    setLogs([]);

    // The /analyze endpoint is now async: it creates the row,
    // returns the jobId, and runs the pipeline in the background.
    // We poll /status/:jobId every 1.5s for live progress logs +
    // the eventual analysis JSON.
    try {
      const ack = await uploadAndAnalyze(file, { jobId: newJob });
      if (!ack?.jobId) throw new Error('No jobId returned');
      beginAnalyzePoll(newJob);
    } catch (err) {
      setErrorMsg(err.message || 'Analysis upload failed');
      setStage("idle");
    }
  };

  // Poll while analyzing. Faster cadence than render because analyze
  // is short (10-15s) so the user sees each step land.
  const beginAnalyzePoll = (id) => {
    const started = Date.now();
    const HARD_CEILING_MS = 90 * 1000;
    if (pollRef.current) clearInterval(pollRef.current);
    pollRef.current = setInterval(async () => {
      try {
        const row = await getRoomStatus(id);
        if (Array.isArray(row?.logs)) setLogs(row.logs);
        if (row?.status === 'analyzed' && row.analysis) {
          clearInterval(pollRef.current);
          pollRef.current = null;
          setAnalysis(row.analysis);
          setStage("analyzed");
        } else if (row?.status === 'failed') {
          clearInterval(pollRef.current);
          pollRef.current = null;
          setErrorMsg(row.error || 'Analyze failed on server');
          setStage("idle");
        } else if (Date.now() - started > HARD_CEILING_MS) {
          clearInterval(pollRef.current);
          pollRef.current = null;
          setErrorMsg('Analyze timed out (>90s)');
          setStage("idle");
        }
      } catch (_) { /* transient — keep polling */ }
    }, 1500);
  };

  const togglePick = (id) => {
    setPicked((s) => {
      const n = new Set(s);
      if (n.has(id)) n.delete(id);
      else n.add(id);
      return n;
    });
  };

  // V2.1 — dispatch the render through the queue, then poll
  // /api/room/status/:jobId every 4s until status becomes
  // 'completed' (mp4Url set) or 'failed'. Worker reports back via
  // /api/gpu-worker/room-{progress,complete,failed}.
  const runRender = async () => {
    if (!jobId) {
      setErrorMsg('Run Analyze first');
      return;
    }
    setStage("rendering");
    setMp4Url(null);
    setErrorMsg(null);
    const items = MOCK_CATALOG.filter((c) => picked.has(c.id));
    try {
      await startRender(jobId, items);
    } catch (err) {
      setErrorMsg(err.message || 'Render dispatch failed');
      setStage("analyzed");
      return;
    }
    beginRenderPoll(jobId);
  };

  const reset = () => {
    if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null; }
    setStage("idle");
    setAnalysis(null);
    setPicked(new Set());
    setJobId(null);
    setMp4Url(null);
    setErrorMsg(null);
  };

  return (
    <div className="relative min-h-screen w-full bg-[var(--luxe-bg-base)] text-fg-primary pt-24 sm:pt-32 pb-16 px-4 sm:px-6 overflow-hidden">
      {/* Ambient glow */}
      <div aria-hidden className="pointer-events-none absolute inset-0">
        <div className="absolute -top-32 left-1/2 -translate-x-1/2 w-[60vw] h-[60vw] rounded-full bg-amber-500/10 blur-[120px]" />
        <div className="absolute bottom-0 right-0 w-[40vw] h-[40vw] rounded-full bg-rose-500/8 blur-[100px]" />
      </div>

      <div className="relative z-10 max-w-6xl mx-auto">
        {/* Heading */}
        <header className="mb-8 sm:mb-10">
          <div className="flex items-center gap-3 mb-3">
            <p className="text-[10px] font-mono uppercase tracking-[0.32em] text-amber-300/80">
              — AI Room Designer
            </p>
            <span className="inline-flex items-center gap-1.5 text-[10px] font-mono uppercase tracking-[0.18em] px-2 py-0.5 rounded-full bg-emerald-500/10 ring-1 ring-emerald-400/30 text-emerald-200">
              <span className="w-1 h-1 rounded-full bg-emerald-300 animate-pulse" />
              V2 · live · BE + worker wired
            </span>
          </div>
          <h1 className="font-poppins font-black tracking-tight text-4xl sm:text-5xl md:text-6xl">
            Show me your room.{" "}
            <span className="text-amber-400">I&apos;ll redesign it.</span>
          </h1>
          <p className="mt-4 max-w-2xl text-gray-300 text-sm sm:text-base leading-relaxed">
            Upload a slow pan of any room. The pipeline pulls keyframes,
            runs object detection + room-layout estimation, asks Groq what&apos;s
            missing, suggests furniture that fits the palette, then composites
            it back in and exports an MP4 of the new room.
          </p>
        </header>

        {/* Resume banner — only when we hydrated from URL / localStorage */}
        {resumed && jobId && (
          <div className="mb-4 rounded-xl ring-1 ring-emerald-400/30 bg-emerald-500/10 px-4 py-2.5 flex items-center gap-3 text-[12px]">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-300 animate-pulse" />
            <span className="text-emerald-100">
              Resumed <code className="text-emerald-200">{jobId}</code> · processing continued on the server while you were away
            </span>
            <button
              onClick={() => {
                if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null; }
                setJobId(null); setAnalysis(null); setPicked(new Set());
                setMp4Url(null); setStage("idle"); setResumed(false);
              }}
              className="ml-auto text-emerald-200/70 hover:text-emerald-100 text-xs"
            >
              × Discard
            </button>
          </div>
        )}

        {/* Step bar */}
        <StepBar stage={stage} />

        {/* Upload zone */}
        {!file && (
          <label
            onDragOver={(e) => e.preventDefault()}
            onDrop={onDrop}
            className="block mt-8 cursor-pointer group"
          >
            <input
              type="file"
              accept="video/*"
              className="hidden"
              onChange={(e) => onPickFile(e.target.files?.[0])}
            />
            <div className="rounded-3xl ring-2 ring-dashed ring-white/15 hover:ring-amber-400/50 bg-white/[0.03] hover:bg-white/[0.05] transition-all px-8 py-16 grid place-items-center text-center min-h-[280px]">
              <div>
                <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-amber-500/15 ring-1 ring-amber-400/30 text-amber-300 text-3xl mb-4">
                  <CloudUploadOutlined />
                </div>
                <p className="text-xl font-semibold text-white">Drop a room video here</p>
                <p className="mt-2 text-sm text-gray-400">
                  10–30 sec phone pan · MP4 / MOV / WEBM · stays in the browser until you hit Analyze
                </p>
              </div>
            </div>
          </label>
        )}

        {/* Working state — video preview + controls */}
        {file && (
          <div className="mt-8 grid grid-cols-1 lg:grid-cols-5 gap-6">
            {/* Video preview */}
            <div className="lg:col-span-3 rounded-2xl overflow-hidden ring-1 ring-white/10 bg-black aspect-video relative">
              <video
                ref={videoRef}
                src={previewUrl}
                controls
                playsInline
                loop
                className="w-full h-full object-contain bg-black"
              />
              {stage === "analyzing" && (
                <div className="absolute inset-0 grid place-items-center bg-black/60 backdrop-blur-sm">
                  <div className="text-center">
                    <div className="inline-block w-8 h-8 rounded-full border-2 border-amber-400/30 border-t-amber-300 animate-spin" />
                    <p className="mt-3 text-sm text-gray-200">Reading the room…</p>
                    <p className="text-[11px] text-gray-500">Keyframes → YOLO → Groq</p>
                  </div>
                </div>
              )}
            </div>

            {/* Side panel — action stack */}
            <div className="lg:col-span-2 space-y-4">
              <ControlPanel
                stage={stage}
                file={file}
                pickedCount={picked.size}
                onAnalyze={runAnalysis}
                onRender={runRender}
                onReset={() => {
                  setFile(null);
                  setPreview("");
                  setStage("idle");
                  setAnalysis(null);
                  setPicked(new Set());
                }}
              />

              {analysis && stage !== "rendering" && stage !== "done" && (
                <AnalysisCard analysis={analysis} />
              )}

              {(stage === "analyzing" || stage === "rendering") && (
                <LogStrip logs={logs} stage={stage} />
              )}
            </div>
          </div>
        )}

        {/* Suggestion catalog — once analyzed */}
        {analysis && (stage === "analyzed" || stage === "rendering" || stage === "done") && (
          <section className="mt-12">
            <div className="flex items-center gap-2 mb-4">
              <ShoppingOutlined className="text-amber-300" />
              <h2 className="text-lg font-semibold text-white">Pick what to add</h2>
              <span className="ml-auto text-[11px] text-gray-500">
                {picked.size} selected
              </span>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-3 gap-3">
              {MOCK_CATALOG.map((item) => {
                const slotMatch = analysis.missing.find((m) => m.label === item.slot);
                const isPicked = picked.has(item.id);
                return (
                  <button
                    key={item.id}
                    onClick={() => togglePick(item.id)}
                    className={`group relative rounded-2xl overflow-hidden ring-1 transition-all text-left ${
                      isPicked
                        ? "ring-amber-400 shadow-[0_0_40px_-8px_rgba(245,158,11,0.5)]"
                        : "ring-white/10 hover:ring-white/30"
                    }`}
                  >
                    <div className="aspect-[4/3] bg-gray-900 overflow-hidden">
                      <img
                        src={item.img}
                        alt={item.label}
                        className="w-full h-full object-cover transition-transform group-hover:scale-105"
                        loading="lazy"
                      />
                    </div>
                    <div className="absolute top-2 left-2 inline-flex items-center gap-1.5 px-2 py-1 rounded-full bg-black/60 backdrop-blur-md text-[10px] font-mono uppercase tracking-[0.18em] text-amber-200">
                      {item.slot}
                    </div>
                    {isPicked && (
                      <div className="absolute top-2 right-2 w-6 h-6 rounded-full bg-amber-400 text-black grid place-items-center">
                        <CheckOutlined className="text-[10px]" />
                      </div>
                    )}
                    <div className="p-3 bg-black/40 backdrop-blur-md">
                      <p className="text-sm font-semibold text-white truncate">{item.label}</p>
                      <p className="text-[11px] text-gray-400 mt-0.5 line-clamp-2">
                        {slotMatch?.why || `${item.tone} tone · ${item.price}`}
                      </p>
                    </div>
                  </button>
                );
              })}
            </div>
          </section>
        )}

        {/* Render result */}
        {stage === "done" && (
          <section className="mt-12 rounded-3xl overflow-hidden ring-1 ring-emerald-400/40 bg-gradient-to-br from-emerald-500/10 via-teal-500/5 to-amber-500/10 p-8">
            <div className="text-center mb-6">
              <div className="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-emerald-500/20 ring-1 ring-emerald-400/40 text-emerald-300 text-2xl mb-4">
                <CheckOutlined />
              </div>
              <h3 className="text-2xl font-poppins font-bold text-white">
                Your new room is rendered.
              </h3>
              <p className="mt-2 text-sm text-gray-300 max-w-md mx-auto">
                Worker composited {picked.size} item{picked.size === 1 ? "" : "s"} into the scene
                and produced a clip below.
              </p>
            </div>
            {mp4Url && (
              <div className="max-w-3xl mx-auto rounded-2xl overflow-hidden ring-1 ring-white/10 bg-black aspect-video">
                <video src={mp4Url} controls playsInline loop className="w-full h-full" />
              </div>
            )}
            <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
              {mp4Url && (
                <a
                  href={mp4Url}
                  target="_blank"
                  rel="noreferrer"
                  download="room-redesign.mp4"
                  className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-black font-bold text-sm transition-colors"
                >
                  <DownloadOutlined /> Download MP4
                </a>
              )}
              <button
                onClick={reset}
                className="inline-flex items-center gap-2 px-5 py-3 rounded-xl border border-white/20 bg-white/[0.04] hover:bg-white/[0.08] text-white font-semibold text-sm transition-all"
              >
                <ReloadOutlined /> Start over
              </button>
            </div>
          </section>
        )}

        {errorMsg && (
          <div className="mt-6 rounded-xl ring-1 ring-rose-400/40 bg-rose-500/10 px-4 py-3 text-sm text-rose-200">
            {errorMsg}
          </div>
        )}

        {/* Pipeline architecture spec — what V2 will actually do. */}
        <PipelineSpec />

        {/* Related lanes */}
        <div className="mt-12 flex flex-wrap items-center justify-center gap-3 text-sm">
          <button
            onClick={() => navigate("/showreel")}
            className="inline-flex items-center gap-2 px-5 py-3 rounded-xl border border-white/15 bg-white/[0.03] hover:bg-white/[0.06] text-white transition-all"
          >
            <PlayCircleOutlined /> Showreel
          </button>
          <button
            onClick={() => navigate("/splat")}
            className="inline-flex items-center gap-2 px-5 py-3 rounded-xl border border-white/15 bg-white/[0.03] hover:bg-white/[0.06] text-white transition-all"
          >
            <AppstoreOutlined /> Splat Viewer
          </button>
          <button
            onClick={() => navigate("/ai-video")}
            className="inline-flex items-center gap-2 px-5 py-3 rounded-xl bg-rose-500 hover:bg-rose-400 text-white font-semibold transition-all"
          >
            <RocketOutlined /> AI Studio
          </button>
        </div>
      </div>
    </div>
  );
}

function StepBar({ stage }) {
  const steps = [
    { key: "upload",    label: "1 · Upload",   icon: <CloudUploadOutlined /> },
    { key: "analyze",   label: "2 · Analyze",  icon: <ExperimentOutlined /> },
    { key: "pick",      label: "3 · Pick",     icon: <ShoppingOutlined /> },
    { key: "render",    label: "4 · Render",   icon: <RocketOutlined /> },
  ];
  const active = {
    idle:       "upload",
    analyzing:  "analyze",
    analyzed:   "pick",
    rendering:  "render",
    done:       "render",
  }[stage];
  const idx = steps.findIndex((s) => s.key === active);
  return (
    <div className="grid grid-cols-4 gap-2 mt-2">
      {steps.map((s, i) => {
        const done   = i < idx;
        const cur    = i === idx;
        return (
          <div
            key={s.key}
            className={`rounded-xl px-3 py-2 text-[11px] flex items-center gap-2 ring-1 ${
              done
                ? "ring-emerald-400/40 bg-emerald-500/10 text-emerald-200"
                : cur
                  ? "ring-amber-400/50 bg-amber-500/10 text-amber-200"
                  : "ring-white/10 bg-white/[0.02] text-gray-500"
            }`}
          >
            <span className="shrink-0">{done ? <CheckOutlined /> : s.icon}</span>
            <span className="truncate uppercase tracking-wider font-mono">{s.label}</span>
          </div>
        );
      })}
    </div>
  );
}

function ControlPanel({ stage, file, pickedCount, onAnalyze, onRender, onReset }) {
  return (
    <div className="rounded-2xl ring-1 ring-white/10 bg-white/[0.03] p-5">
      <div className="flex items-center gap-2 mb-3">
        <HomeOutlined className="text-amber-300" />
        <p className="text-xs font-mono uppercase tracking-[0.22em] text-gray-400">
          Source
        </p>
      </div>
      <p className="text-sm font-semibold text-white truncate" title={file?.name}>
        {file?.name || "—"}
      </p>
      <p className="text-[11px] text-gray-500">
        {file ? `${(file.size / 1024 / 1024).toFixed(1)} MB · ${file.type || "video"}` : ""}
      </p>

      <div className="mt-5 space-y-2">
        {(stage === "idle" || stage === "analyzed") && stage !== "rendering" && stage !== "done" && (
          <button
            onClick={onAnalyze}
            disabled={!file || stage === "analyzing"}
            className="w-full inline-flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-amber-400 disabled:bg-gray-700 disabled:text-gray-500 text-black font-bold text-sm hover:bg-amber-300 transition-colors"
          >
            <ExperimentOutlined />
            {stage === "analyzed" ? "Re-analyze" : "Analyze room"}
          </button>
        )}

        {stage === "analyzed" && (
          <button
            onClick={onRender}
            disabled={pickedCount === 0}
            className="w-full inline-flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-rose-500 disabled:bg-gray-700 disabled:text-gray-500 text-white font-bold text-sm hover:bg-rose-400 transition-colors"
          >
            <RocketOutlined />
            Render new room ({pickedCount})
          </button>
        )}

        {stage === "rendering" && (
          <div className="rounded-xl ring-1 ring-rose-400/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-200 flex items-center gap-3">
            <div className="w-4 h-4 rounded-full border-2 border-rose-400/40 border-t-rose-300 animate-spin" />
            Compositing items into frames…
          </div>
        )}

        <button
          onClick={onReset}
          className="w-full inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl border border-white/15 text-gray-300 hover:text-white hover:bg-white/[0.04] text-xs transition-colors"
        >
          <ReloadOutlined /> Start over
        </button>
      </div>
    </div>
  );
}

// Live transcript of room_jobs progress. Reads the last ~12 lines
// from the polled status payload so the user sees what the pipeline
// is actually doing during analyze (10-15s) and render (60-180s).
function LogStrip({ logs, stage }) {
  const tail = (logs || []).slice(-12);
  return (
    <div className="rounded-2xl ring-1 ring-white/10 bg-black/40 backdrop-blur p-4">
      <div className="flex items-center gap-2 mb-3">
        <div className="w-1.5 h-1.5 rounded-full bg-rose-400 animate-pulse" />
        <p className="text-[10px] font-mono uppercase tracking-[0.22em] text-gray-400">
          Live · {stage === "analyzing" ? "analyze pipeline" : "render pipeline"}
        </p>
      </div>
      {tail.length === 0 ? (
        <p className="text-[11px] text-gray-500 font-mono">waiting for first log line…</p>
      ) : (
        <div className="space-y-1 max-h-[260px] overflow-y-auto pr-1">
          {tail.map((line, i) => {
            const msg = typeof line === "string" ? line : (line?.msg ?? line?.message ?? String(line));
            const ts  = typeof line === "object" && line?.ts ? new Date(line.ts) : null;
            return (
              <div key={i} className="text-[11px] font-mono leading-snug flex gap-2">
                {ts && (
                  <span className="text-gray-600 shrink-0">
                    {ts.toLocaleTimeString([], { hour12: false }).slice(3)}
                  </span>
                )}
                <span className="text-gray-200">{msg}</span>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

function AnalysisCard({ analysis }) {
  return (
    <div className="rounded-2xl ring-1 ring-amber-400/30 bg-gradient-to-br from-amber-500/10 via-rose-500/5 to-transparent p-5">
      <div className="flex items-center gap-2 mb-3">
        <BulbOutlined className="text-amber-300" />
        <p className="text-xs font-mono uppercase tracking-[0.22em] text-amber-200">
          What I see
        </p>
      </div>
      <p className="text-sm font-semibold text-white">{analysis.roomType}</p>
      <ul className="mt-2 text-[12px] text-gray-300 space-y-1">
        {analysis.toneNotes.map((n) => (
          <li key={n} className="flex gap-2">
            <span className="text-amber-300 mt-0.5">·</span>
            <span>{n}</span>
          </li>
        ))}
      </ul>

      <div className="mt-4">
        <p className="text-[10px] font-mono uppercase tracking-[0.22em] text-gray-500 mb-2">
          Detected · {analysis.detected.length} items
        </p>
        <div className="flex flex-wrap gap-1.5">
          {analysis.detected.map((d) => (
            <span
              key={d.label}
              className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-white/[0.04] ring-1 ring-white/10 text-[11px] text-gray-300"
            >
              {d.label}
              <span className="text-[9px] text-gray-500">{Math.round(d.conf * 100)}%</span>
            </span>
          ))}
        </div>
      </div>

      <div className="mt-4">
        <p className="text-[10px] font-mono uppercase tracking-[0.22em] text-rose-300 mb-2">
          Missing · {analysis.spaceGapPct}% unused
        </p>
        <ul className="text-[12px] text-gray-300 space-y-1.5">
          {analysis.missing.map((m) => (
            <li key={m.label}>
              <span className="text-white font-medium">{m.label}</span>
              <span className="text-gray-500"> — {m.why}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

function PipelineSpec() {
  const steps = [
    { n: "01", t: "Keyframe extract",      d: "ffmpeg pulls 6-12 representative frames from the video — covering all four walls." },
    { n: "02", t: "Object detection",      d: "YOLOv8 (already wired in the Python service) tags furniture, fixtures, decor." },
    { n: "03", t: "Room layout + depth",   d: "MiDaS or Depth-Anything estimates 3D extent; gaps → unused-volume map." },
    { n: "04", t: "Groq critique",         d: "Detected items + tone + gaps → LLM picks the 3-5 biggest tasteful improvements." },
    { n: "05", t: "Catalog match",         d: "Suggestions matched to a furniture catalog with image, slot, palette tag, price." },
    { n: "06", t: "Composite + render",    d: "Flux Fill places items at the right depth; LTX/Wan re-animates camera motion; ffmpeg concats to MP4." },
  ];
  return (
    <section className="mt-16">
      <div className="flex items-center gap-2 mb-4">
        <InfoCircleOutlined className="text-gray-400" />
        <h2 className="text-sm font-semibold text-gray-300 uppercase tracking-wider">
          Pipeline · what the worker will do
        </h2>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {steps.map((s) => (
          <div key={s.n} className="rounded-xl ring-1 ring-white/10 bg-white/[0.02] p-4">
            <p className="text-[10px] font-mono uppercase tracking-[0.22em] text-amber-300/70">
              Step {s.n}
            </p>
            <p className="mt-1 text-sm font-semibold text-white">{s.t}</p>
            <p className="mt-1 text-[12px] text-gray-400 leading-relaxed">{s.d}</p>
          </div>
        ))}
      </div>
    </section>
  );
}
