export const ENDPOINTS = {
  // Health
  HEALTH: '/api/health',
  STATS: '/api/stats',

  // AI
  CHAT: '/api/chat',
  AI: '/api/ai',
  GROQ: '/api/groq',
  GEMINI: '/api/gemini',
  GEMINI_VISION: '/api/gemini/vision',
  PROMPT_COACH: '/api/ai/prompt-coach',
  GENERATE_IMAGE: '/api/generate-image',
  IMAGE_EDIT: '/api/image-edit',
  TTS: '/api/tts',
  SUMMARIZE: '/api/summarize',

  // AI Video (queue-based)
  AI_VIDEO_GENERATE: '/api/ai-video/generate',
  AI_VIDEO_STATUS: '/api/ai-video/status',
  AI_VIDEO_TODAY: '/api/ai-video/today',
  AI_VIDEO_LIST: '/api/ai-video/list',
  AI_VIDEO_PROVIDERS: '/api/ai-video/providers',
  AI_VIDEO_UPLOAD_IMAGE: '/api/ai-video/upload-image',
  AI_VIDEO_JOBS:        '/api/ai-video/jobs',
  IMAGE_ENHANCE:        '/api/image-enhance',
  IMAGE_ENHANCE_STATUS: '/api/image-enhance/status',
  IMAGE_ENHANCE_LIST:   '/api/image-enhance/list',
  IMAGE_ENHANCE_BULK:   '/api/image-enhance/bulk',
  AI_VIDEO_BULK:        '/api/ai-video/bulk',
  // Studio lanes (Tier 3)
  LIPSYNC:              '/api/lipsync',
  LIPSYNC_STATUS:       '/api/lipsync/status',
  LIPSYNC_LIST:         '/api/lipsync/list',
  AUDIO:                '/api/audio',
  AUDIO_STATUS:         '/api/audio/status',
  AUDIO_LIST:           '/api/audio/list',
  CINEMA:               '/api/cinema',
  CINEMA_STATUS:        '/api/cinema/status',
  CINEMA_LIST:          '/api/cinema/list',
  JOB_LOGS:             '/api/job-logs',   // /:lane/:jobId?since=<ms>&limit=80

  // Vision
  FACE_ANALYZE: '/api/face-analyze',
  DETECT_OBJECTS: '/api/detect-objects',
  FACE_HEALTH: '/api/face-health',

  // NASA — direct proxied endpoints (api.nasa.gov/*)
  APOD: '/api/nasa/planetary/apod',
  NEOWS: '/api/nasa/neo/rest/v1/feed',
  DONKI_FLR: '/api/nasa/DONKI/FLR',
  DONKI_GST: '/api/nasa/DONKI/GST',
  DONKI_CME: '/api/nasa/DONKI/CME',
  EPIC: '/api/nasa/EPIC/api/natural',
  EPIC_ALL: '/api/nasa/EPIC/api/natural/all',
  EPIC_DATE: '/api/nasa/EPIC/api/natural/date', // append /{date}
  EARTH_IMAGERY: '/api/nasa/planetary/earth/imagery',

  // Third-party proxied endpoints
  FIREBALL: '/api/proxy/fireball',
  ISS: '/api/proxy/iss',
  ASTROS: '/api/proxy/astros',
  TLE: '/api/proxy/tle',
  EONET: '/api/proxy/eonet',
  IMAGES: '/api/proxy/images',
  TECHTRANSFER: '/api/proxy/techtransfer',
  POKEMON_LIST: '/api/proxy/pokemon',
  POKEMON_DETAIL: '/api/proxy/pokemon-detail',
  ARTWORKS: '/api/proxy/artworks',
  WEATHER: '/api/proxy/weather',
  FORECAST: '/api/proxy/forecast',
  SUNRISE: '/api/proxy/sunrise',
  RICKMORTY: '/api/proxy/rickmorty',
  RICKMORTY_DETAIL: '/api/proxy/rickmorty-detail',
  RANDOM_DOG: '/api/proxy/randomdog',
  DOG_BREEDS: '/api/proxy/dogbreeds',
  DOG_BREED: '/api/proxy/dogbreed',
  QUOTES: '/api/proxy/quotes',
  COUNTRIES: '/api/proxy/countries',
  COUNTRY: '/api/proxy/country',
  MEMES: '/api/proxy/memes',
  LAUNCHES: '/api/proxy/launches',
  FOODISH: '/api/proxy/foodish',
  MTG: '/api/proxy/mtg',
};
